# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# ============================================================
# PROYECTO 2 - BLOQUE 1: Dataset y features
# ============================================================
"""

!pip install yfinance -q

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Definir universo de activos (más amplio que antes)

tickers = ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]

start_date = "2015-01-01"
end_date = "2025-12-31"

# 2. Descargar precios

data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=True)
prices = data["Close"].dropna()

# 3. Retornos logarítmicos

returns = np.log(prices / prices.shift(1)).dropna()

# 4. Crear features (muy importante para ML)

# Lagged returns
# The original code produced an error because returns.shift(i) returns a DataFrame with multiple columns (one for each ticker),
# but it was being assigned to a single new column 'lag_i'.
# To fix this, we will calculate the average daily return across all assets, and then apply the lag to this series.
daily_mean_returns = returns.mean(axis=1) # Calculate the mean return across all assets for each day
for i in range(1, 6):
    returns[f"lag_{i}"] = daily_mean_returns.shift(i)

# Rolling mean
# This line works correctly as it calculates a single series (mean across axis=1, then rolling mean).
returns["rolling_mean_5"] = returns.mean(axis=1).rolling(5).mean()

# Rolling volatility
# This line also works correctly for the same reason.
returns["rolling_vol_5"] = returns.std(axis=1).rolling(5).mean()

returns = returns.dropna()

# 5. Separar X (features) y y (target)

X = returns.drop(columns=tickers)
y = returns[tickers].shift(-1)

data_ml = pd.concat([X, y], axis=1).dropna()

X = data_ml[X.columns]
y = data_ml[tickers]

# 6. Train/Test split

split_date = "2022-01-01"

X_train = X[X.index < split_date]
X_test = X[X.index >= split_date]

y_train = y[y.index < split_date]
y_test = y[y.index >= split_date]

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

"""# ============================================================
# BLOQUE 2: Predict returns (baseline)
# ============================================================
"""

from sklearn.linear_model import LinearRegression

# 1. Modelo

model = LinearRegression()
model.fit(X_train, y_train)

# 2. Predicciones

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

y_pred_test = pd.DataFrame(y_pred_test, index=y_test.index, columns=tickers)

"""# ============================================================
# BLOQUE 3: Portafolio Markowitz simple
# ============================================================
"""

def optimize_portfolio(returns_pred):

    # Long-only + suma 1
    weights = returns_pred.clip(lower=0)

    if weights.sum() == 0:
        weights = np.ones(len(weights)) / len(weights)
    else:
        weights = weights / weights.sum()

    return weights

# 1. Generar pesos diarios

weights_p_to = y_pred_test.apply(optimize_portfolio, axis=1)

# 2. Retornos reales

portfolio_returns_pto = (weights_p_to.shift(1) * y_test).sum(axis=1)
portfolio_returns_pto = portfolio_returns_pto.dropna()

# 3. Curva acumulada

pto_cum = (1 + portfolio_returns_pto).cumprod()

plt.figure(figsize=(12,5))
plt.plot(pto_cum)
plt.title("Predict-then-Optimize (PtO)")
plt.grid(True)
plt.show()

"""# ============================================================
# BLOQUE 4: SPO simplificado / Decision-Focused Learning
# ============================================================

!pip install torch -q
"""

import torch
import torch.nn as nn
import torch.optim as optim

# 1. Convertir datos a tensores

X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

# 2. Modelo simple:
# Recibe features y produce pesos long-only que suman 1

class SimpleSPO(nn.Module):
    def __init__(self, input_dim, n_assets):
        super(SimpleSPO, self).__init__()
        self.linear = nn.Linear(input_dim, n_assets)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        scores = self.linear(x)
        weights = self.softmax(scores)
        return weights

# 3. Inicializar modelo

input_dim = X_train.shape[1]
n_assets = len(tickers)

spo_model = SimpleSPO(input_dim, n_assets)
optimizer = optim.Adam(spo_model.parameters(), lr=0.001)

# 4. Loss decision-focused
# En vez de minimizar error de predicción, maximizamos retorno del portafolio

def spo_loss(weights, realized_returns):
    portfolio_returns = torch.sum(weights * realized_returns, dim=1)
    loss = -torch.mean(portfolio_returns)
    return loss

# 5. Entrenamiento

epochs = 300

for epoch in range(epochs):
    spo_model.train()

    optimizer.zero_grad()

    weights_train = spo_model(X_train_tensor)
    loss = spo_loss(weights_train, y_train_tensor)

    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.6f}")

# 6. Obtener pesos en test

spo_model.eval()

with torch.no_grad():
    weights_spo_test = spo_model(X_test_tensor)

weights_spo_test = pd.DataFrame(
    weights_spo_test.numpy(),
    index=X_test.index,
    columns=tickers
)

display(weights_spo_test.head())

# 7. Retornos del portafolio SPO simplificado

portfolio_returns_spo = (weights_spo_test.shift(1) * y_test).sum(axis=1)
portfolio_returns_spo = portfolio_returns_spo.dropna()

spo_cum = (1 + portfolio_returns_spo).cumprod()

# 8. Comparar PtO vs SPO simplificado

plt.figure(figsize=(12, 5))

plt.plot(pto_cum.index, pto_cum, label="Predict-then-Optimize")
plt.plot(spo_cum.index, spo_cum, label="SPO simplificado")

plt.title("Comparación: PtO vs SPO simplificado")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

def calculate_metrics(strategy_returns):
    cumulative = (1 + strategy_returns).cumprod()

    annual_return = strategy_returns.mean() * 252
    annual_volatility = strategy_returns.std() * np.sqrt(252)
    sharpe = annual_return / annual_volatility

    drawdown = cumulative / cumulative.cummax() - 1
    max_drawdown = drawdown.min()

    total_return = cumulative.iloc[-1] - 1

    return annual_return, annual_volatility, sharpe, max_drawdown, total_return

# 9. Métricas comparativas

comparison_spo = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "PtO": calculate_metrics(portfolio_returns_pto),
    "SPO Simplificado": calculate_metrics(portfolio_returns_spo)
})

display(comparison_spo)

# 10. Formato legible

comparison_spo_formatted = comparison_spo.copy()

for col in ["PtO", "SPO Simplificado"]:
    comparison_spo_formatted[col] = comparison_spo_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(comparison_spo_formatted)

"""# ============================================================
# BLOQUE 5: Costos de transacción, turnover y concentración
# ============================================================
"""

# 1. Función para calcular turnover

def calculate_turnover(weights):
    turnover = weights.diff().abs().sum(axis=1)
    turnover = turnover.fillna(0)
    return turnover

# 2. Función para calcular retornos netos de costos

def calculate_portfolio_returns_with_costs(weights, realized_returns, transaction_cost=0.005):

    gross_returns = (weights.shift(1) * realized_returns).sum(axis=1)
    gross_returns = gross_returns.dropna()

    turnover = calculate_turnover(weights)
    turnover = turnover.reindex(gross_returns.index).fillna(0)

    costs = transaction_cost * turnover

    net_returns = gross_returns - costs

    return net_returns, gross_returns, costs, turnover

# 3. Aplicar costos a PtO y SPO simplificado

transaction_cost = 0.005  # igual al paper: 0.5%

pto_net_returns, pto_gross_returns, pto_costs, pto_turnover = calculate_portfolio_returns_with_costs(
    weights_p_to,
    y_test,
    transaction_cost=transaction_cost
)

spo_net_returns, spo_gross_returns, spo_costs, spo_turnover = calculate_portfolio_returns_with_costs(
    weights_spo_test,
    y_test,
    transaction_cost=transaction_cost
)

# 4. Curvas acumuladas netas

pto_net_cum = (1 + pto_net_returns).cumprod()
spo_net_cum = (1 + spo_net_returns).cumprod()

plt.figure(figsize=(12, 5))

plt.plot(pto_net_cum.index, pto_net_cum, label="PtO neto de costos")
plt.plot(spo_net_cum.index, spo_net_cum, label="SPO simplificado neto de costos")

plt.title("PtO vs SPO simplificado - Retornos netos de costos")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 5. Comparación de métricas netas

cost_adjusted_comparison = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "PtO Net": calculate_metrics(pto_net_returns),
    "SPO Net": calculate_metrics(spo_net_returns)
})

display(cost_adjusted_comparison)

# 6. Formato legible

cost_adjusted_comparison_formatted = cost_adjusted_comparison.copy()

for col in ["PtO Net", "SPO Net"]:
    cost_adjusted_comparison_formatted[col] = cost_adjusted_comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(cost_adjusted_comparison_formatted)

# 7. Comparar turnover promedio

turnover_summary = pd.DataFrame({
    "Strategy": ["PtO", "SPO Simplificado"],
    "Average Turnover": [
        pto_turnover.mean(),
        spo_turnover.mean()
    ],
    "Total Turnover": [
        pto_turnover.sum(),
        spo_turnover.sum()
    ],
    "Total Transaction Costs": [
        pto_costs.sum(),
        spo_costs.sum()
    ]
})

display(turnover_summary)

# 8. Concentración del portafolio: Herfindahl-Hirschman Index

def calculate_hhi(weights):
    hhi = (weights ** 2).sum(axis=1)
    return hhi

pto_hhi = calculate_hhi(weights_p_to)
spo_hhi = calculate_hhi(weights_spo_test)

hhi_summary = pd.DataFrame({
    "Strategy": ["PtO", "SPO Simplificado"],
    "Average HHI": [
        pto_hhi.mean(),
        spo_hhi.mean()
    ],
    "Max HHI": [
        pto_hhi.max(),
        spo_hhi.max()
    ]
})

display(hhi_summary)

# 9. Graficar concentración en el tiempo

plt.figure(figsize=(12, 5))

plt.plot(pto_hhi.index, pto_hhi, label="PtO HHI")
plt.plot(spo_hhi.index, spo_hhi, label="SPO HHI")

plt.title("Concentración del portafolio en el tiempo")
plt.xlabel("Fecha")
plt.ylabel("HHI")
plt.legend()
plt.grid(True)
plt.show()

"""# ============================================================
# BLOQUE 6: Análisis de pesos del portafolio
# Objetivo: entender cómo asigna capital cada estrategia
# ============================================================
"""

# 1. Graficar evolución de pesos PtO

plt.figure(figsize=(12, 6))

for ticker in tickers:
    plt.plot(weights_p_to.index, weights_p_to[ticker], label=ticker)

plt.title("Evolución de pesos - PtO")
plt.xlabel("Fecha")
plt.ylabel("Peso")
plt.legend()
plt.grid(True)
plt.show()

# 2. Graficar evolución de pesos SPO simplificado

plt.figure(figsize=(12, 6))

for ticker in tickers:
    plt.plot(weights_spo_test.index, weights_spo_test[ticker], label=ticker)

plt.title("Evolución de pesos - SPO simplificado")
plt.xlabel("Fecha")
plt.ylabel("Peso")
plt.legend()
plt.grid(True)
plt.show()

# 3. Pesos promedio por estrategia

avg_weights_comparison = pd.DataFrame({
    "PtO Average Weight": weights_p_to.mean(),
    "SPO Average Weight": weights_spo_test.mean()
})

display(avg_weights_comparison)

# 4. Pesos mínimos y máximos por estrategia

weight_ranges = pd.DataFrame({
    "PtO Min": weights_p_to.min(),
    "PtO Max": weights_p_to.max(),
    "SPO Min": weights_spo_test.min(),
    "SPO Max": weights_spo_test.max()
})

display(weight_ranges)

# 5. Activo dominante por día

pto_dominant_asset = weights_p_to.idxmax(axis=1)
spo_dominant_asset = weights_spo_test.idxmax(axis=1)

dominant_summary = pd.DataFrame({
    "PtO Dominant Asset": pto_dominant_asset.value_counts(),
    "SPO Dominant Asset": spo_dominant_asset.value_counts()
}).fillna(0)

display(dominant_summary)

# 6. Participación promedio visual

avg_weights_comparison.plot(kind="bar", figsize=(10, 5))

plt.title("Pesos promedio por activo")
plt.xlabel("Activo")
plt.ylabel("Peso promedio")
plt.grid(True)
plt.show()

# 7. Comparar pesos iniciales y finales

initial_final_weights = pd.DataFrame({
    "PtO Initial": weights_p_to.iloc[0],
    "PtO Final": weights_p_to.iloc[-1],
    "SPO Initial": weights_spo_test.iloc[0],
    "SPO Final": weights_spo_test.iloc[-1]
})

display(initial_final_weights)

"""# ============================================================
# BLOQUE 7: Performance por régimen de mercado
# ============================================================
"""

# Usamos promedio de retornos como proxy de mercado

market_returns = y_test.mean(axis=1)
market_cum = (1 + market_returns).cumprod()

plt.figure(figsize=(12,5))
plt.plot(market_cum)
plt.title("Proxy de mercado (promedio activos)")
plt.grid(True)
plt.show()

# Definir tendencia usando media móvil

rolling_window = 60

market_trend = market_cum.rolling(rolling_window).mean()

regime = pd.Series(index=market_cum.index)

regime[market_cum > market_trend] = "Bull"
regime[market_cum < market_trend] = "Bear"
regime = regime.fillna("Neutral")

display(regime.value_counts())

def get_regime_returns(returns, regime_series, regime_name):
    mask = regime_series == regime_name
    return returns[mask]

regimes = ["Bull", "Bear", "Neutral"]

results_regime = []

for r in regimes:

    pto_r = get_regime_returns(portfolio_returns_pto, regime, r)
    spo_r = get_regime_returns(portfolio_returns_spo, regime, r)

    if len(pto_r) > 0:
        pto_metrics = calculate_metrics(pto_r)
        spo_metrics = calculate_metrics(spo_r)

        results_regime.append({
            "Regime": r,
            "PtO Sharpe": pto_metrics[2],
            "SPO Sharpe": spo_metrics[2],
            "PtO Return": pto_metrics[0],
            "SPO Return": spo_metrics[0]
        })

regime_df = pd.DataFrame(results_regime)
display(regime_df)

plt.figure(figsize=(10,5))

plt.bar(regime_df["Regime"], regime_df["PtO Sharpe"], alpha=0.6, label="PtO")
plt.bar(regime_df["Regime"], regime_df["SPO Sharpe"], alpha=0.6, label="SPO")

plt.title("Sharpe por régimen de mercado")
plt.legend()
plt.grid(True)
plt.show()

"""# ============================================================
# BLOQUE 8: Rolling Window para SPO simplificado vs PtO
# ============================================================
"""

# 1. Parámetros rolling

train_window = 252      # 1 año de entrenamiento
test_window = 21        # 1 mes de prueba
step_size = 21          # rebalanceo mensual

epochs = 150
learning_rate = 0.001

# 2. Función para entrenar SPO en cada ventana

def train_spo_model(X_train_w, y_train_w, input_dim, n_assets, epochs=150, lr=0.001):

    X_tensor = torch.tensor(X_train_w.values, dtype=torch.float32)
    y_tensor = torch.tensor(y_train_w.values, dtype=torch.float32)

    model = SimpleSPO(input_dim, n_assets)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        weights = model(X_tensor)
        loss = spo_loss(weights, y_tensor)

        loss.backward()
        optimizer.step()

    return model

# 3. Función para entrenar PtO en cada ventana

def train_pto_model(X_train_w, y_train_w):
    model = LinearRegression()
    model.fit(X_train_w, y_train_w)
    return model

# 4. Ejecutar rolling window

rolling_pto_returns = []
rolling_spo_returns = []

rolling_pto_weights = []
rolling_spo_weights = []

rolling_dates = []

for start in range(0, len(X) - train_window - test_window, step_size):

    train_start = start
    train_end = start + train_window
    test_end = train_end + test_window

    X_train_w = X.iloc[train_start:train_end]
    y_train_w = y.iloc[train_start:train_end]

    X_test_w = X.iloc[train_end:test_end]
    y_test_w = y.iloc[train_end:test_end]

    # PtO
    pto_model_w = train_pto_model(X_train_w, y_train_w)
    y_pred_w = pd.DataFrame(
        pto_model_w.predict(X_test_w),
        index=X_test_w.index,
        columns=tickers
    )

    weights_pto_w = y_pred_w.apply(optimize_portfolio, axis=1)
    returns_pto_w = (weights_pto_w.shift(1) * y_test_w).sum(axis=1).dropna()

    # SPO
    spo_model_w = train_spo_model(
        X_train_w,
        y_train_w,
        input_dim=input_dim,
        n_assets=n_assets,
        epochs=epochs,
        lr=learning_rate
    )

    X_test_tensor_w = torch.tensor(X_test_w.values, dtype=torch.float32)

    with torch.no_grad():
        weights_spo_w_tensor = spo_model_w(X_test_tensor_w)

    weights_spo_w = pd.DataFrame(
        weights_spo_w_tensor.numpy(),
        index=X_test_w.index,
        columns=tickers
    )

    returns_spo_w = (weights_spo_w.shift(1) * y_test_w).sum(axis=1).dropna()

    rolling_pto_returns.append(returns_pto_w)
    rolling_spo_returns.append(returns_spo_w)

    rolling_pto_weights.append(weights_pto_w)
    rolling_spo_weights.append(weights_spo_w)

    rolling_dates.append(X_test_w.index[0])

# 5. Consolidar retornos rolling

rolling_pto_returns = pd.concat(rolling_pto_returns).sort_index()
rolling_spo_returns = pd.concat(rolling_spo_returns).sort_index()

rolling_pto_cum = (1 + rolling_pto_returns).cumprod()
rolling_spo_cum = (1 + rolling_spo_returns).cumprod()

# 6. Graficar rolling performance

plt.figure(figsize=(12, 5))

plt.plot(rolling_pto_cum.index, rolling_pto_cum, label="PtO Rolling")
plt.plot(rolling_spo_cum.index, rolling_spo_cum, label="SPO Rolling")

plt.title("Rolling Window Performance: PtO vs SPO")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 7. Métricas rolling

rolling_comparison = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "PtO Rolling": calculate_metrics(rolling_pto_returns),
    "SPO Rolling": calculate_metrics(rolling_spo_returns)
})

display(rolling_comparison)

# 8. Formato legible

rolling_comparison_formatted = rolling_comparison.copy()

for col in ["PtO Rolling", "SPO Rolling"]:
    rolling_comparison_formatted[col] = rolling_comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(rolling_comparison_formatted)

# 9. Consolidar pesos rolling

rolling_pto_weights_df = pd.concat(rolling_pto_weights).sort_index()[tickers]
rolling_spo_weights_df = pd.concat(rolling_spo_weights).sort_index()[tickers]

# 10. Turnover rolling

rolling_pto_turnover = calculate_turnover(rolling_pto_weights_df)
rolling_spo_turnover = calculate_turnover(rolling_spo_weights_df)

turnover_rolling_summary = pd.DataFrame({
    "Strategy": ["PtO Rolling", "SPO Rolling"],
    "Average Turnover": [
        rolling_pto_turnover.mean(),
        rolling_spo_turnover.mean()
    ],
    "Total Turnover": [
        rolling_pto_turnover.sum(),
        rolling_spo_turnover.sum()
    ]
})

display(turnover_rolling_summary)