# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# ============================================================
# PROYECTO 3 - BLOQUE 1: Simulación GBM + opción
# ============================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm

# Parámetros del activo

S0 = 100
K = 100
T = 0.25      # 3 meses
r = 0.0
sigma = 0.2

dt = 1/252
N = int(T / dt)

n_paths = 1000

def simulate_gbm(S0, r, sigma, T, dt, n_paths):

    N = int(T / dt)
    paths = np.zeros((N, n_paths))
    paths[0] = S0

    for t in range(1, N):
        z = np.random.normal(size=n_paths)
        paths[t] = paths[t-1] * np.exp((r - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*z)

    return paths

paths = simulate_gbm(S0, r, sigma, T, dt, n_paths)

plt.figure(figsize=(10,5))

for i in range(10):
    plt.plot(paths[:, i])

plt.title("Simulación GBM del subyacente")
plt.xlabel("Tiempo")
plt.ylabel("Precio")
plt.grid(True)
plt.show()

def bs_call_price(S, K, T, r, sigma):
    if T <= 0:
        return max(S - K, 0)

    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
    d2 = d1 - sigma*np.sqrt(T)

    return S*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)

def bs_delta(S, K, T, r, sigma):
    if T <= 0:
        return 1.0 if S > K else 0.0

    d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
    return norm.cdf(d1)

"""# ============================================================
# PROYECTO 3 - BLOQUE 2: Delta Hedging baseline
# ============================================================
"""

# 1. Parámetros de costos

transaction_cost = 0.01  # 1% del valor transado, similar al ejemplo MATLAB

# 2. Función para evaluar delta hedging en una trayectoria

def delta_hedging_path(path, K, T, r, sigma, dt, transaction_cost):

    n_steps = len(path)

    option_values = []
    deltas = []

    cash = 0
    hedge_position = 0

    # Precio inicial de la opción
    option_price_0 = bs_call_price(path[0], K, T, r, sigma)

    # Vendemos la opción y recibimos prima
    cash += option_price_0

    for t in range(n_steps):
        tau = max(T - t * dt, 0)
        S = path[t]

        option_value = bs_call_price(S, K, tau, r, sigma)
        delta = bs_delta(S, K, tau, r, sigma)

        option_values.append(option_value)
        deltas.append(delta)

        # Rebalancear hedge hacia delta
        trade = delta - hedge_position
        cost = abs(trade) * S * transaction_cost

        cash -= trade * S
        cash -= cost

        hedge_position = delta

    # Liquidación final
    S_T = path[-1]
    payoff = max(S_T - K, 0)

    # Cerrar hedge
    cash += hedge_position * S_T
    cash -= abs(hedge_position) * S_T * transaction_cost

    # Pagamos payoff de la opción vendida
    cash -= payoff

    final_pnl = cash

    return final_pnl, np.array(option_values), np.array(deltas)

# 3. Ejecutar delta hedging en todas las trayectorias

transaction_cost = 0.001

delta_pnls = []
all_deltas = []

for i in range(n_paths):
    pnl, option_values, deltas = delta_hedging_path(
        paths[:, i],
        K,
        T,
        r,
        sigma,
        dt,
        transaction_cost
    )

    delta_pnls.append(pnl)
    all_deltas.append(deltas)

delta_pnls = np.array(delta_pnls)

# 4. Métricas del baseline

delta_results = pd.DataFrame({
    "Metric": [
        "Average PnL",
        "Median PnL",
        "PnL Std",
        "5% Worst PnL",
        "95% Best PnL"
    ],
    "Delta Hedging": [
        delta_pnls.mean(),
        np.median(delta_pnls),
        delta_pnls.std(),
        np.percentile(delta_pnls, 5),
        np.percentile(delta_pnls, 95)
    ]
})

display(delta_results)

# 5. Histograma de PnL

plt.figure(figsize=(10, 5))
plt.hist(delta_pnls, bins=40, alpha=0.7)

plt.title("Distribución de PnL - Delta Hedging")
plt.xlabel("PnL final")
plt.ylabel("Frecuencia")
plt.grid(True)
plt.show()

# 6. Visualizar delta en una trayectoria ejemplo

example_path = 0
example_deltas = all_deltas[example_path]

plt.figure(figsize=(10, 5))
plt.plot(example_deltas)

plt.title("Delta hedge ratio - trayectoria ejemplo")
plt.xlabel("Tiempo")
plt.ylabel("Delta")
plt.grid(True)
plt.show()

"""# ============================================================
# PROYECTO 3 - BLOQUE 3: Entorno RL para hedging
# ============================================================
"""

# 1. Función para simular una sola trayectoria

def simulate_single_gbm(S0, r, sigma, T, dt):
    N = int(T / dt)
    path = np.zeros(N)
    path[0] = S0

    for t in range(1, N):
        z = np.random.normal()
        path[t] = path[t-1] * np.exp((r - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z)

    return path

# 2. Clase del entorno de hedging

class HedgingEnv:
    def __init__(self, S0, K, T, r, sigma, dt, transaction_cost):
        self.S0 = S0
        self.K = K
        self.T = T
        self.r = r
        self.sigma = sigma
        self.dt = dt
        self.transaction_cost = transaction_cost
        self.N = int(T / dt)
        self.reset()

    def reset(self):
        self.path = simulate_single_gbm(
            self.S0, self.r, self.sigma, self.T, self.dt
        )
        self.t = 0
        self.position = 0.0

        return self._get_state()

    def _get_state(self):
        S = self.path[self.t]
        tau = max(self.T - self.t * self.dt, 0)

        moneyness = S / self.K

        state = np.array([
            moneyness,
            tau,
            self.position
        ], dtype=np.float32)

        return state

    def step(self, action):
        # Acción = hedge ratio entre 0 y 1
        action = float(np.clip(action, 0, 1))

        S_t = self.path[self.t]
        tau_t = max(self.T - self.t * self.dt, 0)
        V_t = bs_call_price(S_t, self.K, tau_t, self.r, self.sigma)

        previous_position = self.position
        new_position = action

        # Avanzar tiempo
        self.t += 1
        done = self.t >= self.N - 1

        S_next = self.path[self.t]
        tau_next = max(self.T - self.t * self.dt, 0)
        V_next = bs_call_price(S_next, self.K, tau_next, self.r, self.sigma)

        # P&L del hedge, inspirado en el PDF de MathWorks
        hedge_pnl = previous_position * (S_next - S_t)
        option_pnl = -(V_next - V_t)
        trading_cost = self.transaction_cost * abs(new_position - previous_position) * S_next

        reward = hedge_pnl + option_pnl - trading_cost

        # Penalización por swings grandes de P&L
        reward = reward - 1.5 * reward**2

        self.position = new_position

        next_state = self._get_state()

        return next_state, reward, done, {
            "S": S_next,
            "option_value": V_next,
            "position": self.position,
            "trading_cost": trading_cost
        }

# 3. Probar el entorno con acciones aleatorias

env = HedgingEnv(
    S0=S0,
    K=K,
    T=T,
    r=r,
    sigma=sigma,
    dt=dt,
    transaction_cost=transaction_cost
)

state = env.reset()
print("Estado inicial:", state)

total_reward = 0

for step in range(env.N - 1):
    random_action = np.random.rand()
    next_state, reward, done, info = env.step(random_action)
    total_reward += reward

    if done:
        break

print("Reward total con política aleatoria:", total_reward)

"""# ============================================================
# PROYECTO 3 - BLOQUE 4: Entrenamiento de agente RL simple
# ============================================================
"""

import torch
import torch.nn as nn
import torch.optim as optim

# 1. Red neuronal de política
# Input: estado [moneyness, tau, posición actual]
# Output: hedge ratio entre 0 y 1

class HedgePolicy(nn.Module):
    def __init__(self, state_dim=3, hidden_dim=64):
        super(HedgePolicy, self).__init__()

        self.network = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid()
        )

    def forward(self, state):
        return self.network(state)

# 2. Inicializar agente

policy = HedgePolicy()
optimizer = optim.Adam(policy.parameters(), lr=0.001)

# 3. Función para correr un episodio

def run_episode(env, policy):
    states = []
    actions = []
    rewards = []

    state = env.reset()
    done = False

    while not done:
        state_tensor = torch.tensor(state, dtype=torch.float32).unsqueeze(0)

        # Acción determinística base
        action_mean = policy(state_tensor)

        # Añadimos exploración con ruido
        noise = torch.normal(mean=0.0, std=0.10, size=action_mean.shape)
        action = torch.clamp(action_mean + noise, 0, 1)

        next_state, reward, done, info = env.step(action.item())

        states.append(state_tensor)
        actions.append(action)
        rewards.append(reward)

        state = next_state

    return states, actions, rewards

# 4. Discounted rewards

def compute_discounted_rewards(rewards, gamma=0.99):
    discounted = []
    cumulative = 0

    for rwd in reversed(rewards):
        cumulative = rwd + gamma * cumulative
        discounted.insert(0, cumulative)

    discounted = torch.tensor(discounted, dtype=torch.float32)

    if discounted.std() > 0:
        discounted = (discounted - discounted.mean()) / (discounted.std() + 1e-8)

    return discounted

# 5. Entrenamiento

n_episodes = 1000
gamma = 0.99

episode_rewards = []

for episode in range(n_episodes):
    states, actions, rewards = run_episode(env, policy)
    discounted_rewards = compute_discounted_rewards(rewards, gamma=gamma)

    loss = 0

    for state_tensor, action, Gt in zip(states, actions, discounted_rewards):
        action_pred = policy(state_tensor)

        # Loss simplificada: empuja acciones hacia las que generaron mayor reward
        loss += ((action_pred - action.detach()) ** 2 * (-Gt)).mean()

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    episode_rewards.append(sum(rewards))

    if episode % 100 == 0:
        print(f"Episode {episode}, Reward: {sum(rewards):.4f}")

# 6. Graficar evolución del reward

plt.figure(figsize=(10, 5))
plt.plot(pd.Series(episode_rewards).rolling(50).mean())

plt.title("Reward promedio móvil durante entrenamiento")
plt.xlabel("Episodio")
plt.ylabel("Reward")
plt.grid(True)
plt.show()

# 7. Política aprendida vs Delta BSM

moneyness_grid = np.linspace(0.8, 1.2, 100)
tau_fixed = T / 2

rl_actions = []
bsm_deltas = []

policy.eval()

for m in moneyness_grid:
    state = torch.tensor([[m, tau_fixed, 0.5]], dtype=torch.float32)

    with torch.no_grad():
        rl_action = policy(state).item()

    S = m * K
    delta = bs_delta(S, K, tau_fixed, r, sigma)

    rl_actions.append(rl_action)
    bsm_deltas.append(delta)

plt.figure(figsize=(10, 5))
plt.plot(moneyness_grid, bsm_deltas, label="Delta BSM")
plt.plot(moneyness_grid, rl_actions, label="RL Hedge")

plt.title("Política aprendida vs Delta BSM")
plt.xlabel("Moneyness S/K")
plt.ylabel("Hedge Ratio")
plt.legend()
plt.grid(True)
plt.show()

"""# ============================================================
# PROYECTO 3 - BLOQUE 5: Comparación RL vs Delta Hedging
# ============================================================
"""

# 1. Función para evaluar política RL en una trayectoria

def rl_hedging_path(path, policy, K, T, r, sigma, dt, transaction_cost):

    n_steps = len(path)

    cash = 0
    hedge_position = 0

    option_price_0 = bs_call_price(path[0], K, T, r, sigma)
    cash += option_price_0

    rl_positions = []

    policy.eval()

    for t in range(n_steps):
        S = path[t]
        tau = max(T - t * dt, 0)
        moneyness = S / K

        state = torch.tensor([[moneyness, tau, hedge_position]], dtype=torch.float32)

        with torch.no_grad():
            new_position = policy(state).item()

        trade = new_position - hedge_position
        cost = abs(trade) * S * transaction_cost

        cash -= trade * S
        cash -= cost

        hedge_position = new_position
        rl_positions.append(hedge_position)

    S_T = path[-1]
    payoff = max(S_T - K, 0)

    cash += hedge_position * S_T
    cash -= abs(hedge_position) * S_T * transaction_cost
    cash -= payoff

    final_pnl = cash

    return final_pnl, np.array(rl_positions)

# 2. Simular nuevas trayectorias para test

n_test_paths = 1000
test_paths = simulate_gbm(S0, r, sigma, T, dt, n_test_paths)

# 3. Evaluar Delta Hedging y RL

delta_test_pnls = []
rl_test_pnls = []

delta_positions_all = []
rl_positions_all = []

for i in range(n_test_paths):

    delta_pnl, _, delta_positions = delta_hedging_path(
        test_paths[:, i],
        K,
        T,
        r,
        sigma,
        dt,
        transaction_cost
    )

    rl_pnl, rl_positions = rl_hedging_path(
        test_paths[:, i],
        policy,
        K,
        T,
        r,
        sigma,
        dt,
        transaction_cost
    )

    delta_test_pnls.append(delta_pnl)
    rl_test_pnls.append(rl_pnl)

    delta_positions_all.append(delta_positions)
    rl_positions_all.append(rl_positions)

delta_test_pnls = np.array(delta_test_pnls)
rl_test_pnls = np.array(rl_test_pnls)

comparison_hedging = pd.DataFrame({
    "Metric": [
        "Average PnL",
        "Median PnL",
        "PnL Std",
        "5% Worst PnL",
        "95% Best PnL"
    ],
    "Delta Hedging": [
        delta_test_pnls.mean(),
        np.median(delta_test_pnls),
        delta_test_pnls.std(),
        np.percentile(delta_test_pnls, 5),
        np.percentile(delta_test_pnls, 95)
    ],
    "RL Hedging": [
        rl_test_pnls.mean(),
        np.median(rl_test_pnls),
        rl_test_pnls.std(),
        np.percentile(rl_test_pnls, 5),
        np.percentile(rl_test_pnls, 95)
    ]
})

display(comparison_hedging)

# 5. Histograma comparativo

plt.figure(figsize=(10, 5))

plt.hist(delta_test_pnls, bins=40, alpha=0.6, label="Delta Hedging")
plt.hist(rl_test_pnls, bins=40, alpha=0.6, label="RL Hedging")

plt.title("Distribución de PnL: Delta Hedging vs RL")
plt.xlabel("PnL final")
plt.ylabel("Frecuencia")
plt.legend()
plt.grid(True)
plt.show()

# 6. Comparar hedge ratios promedio

avg_delta_positions = np.mean(delta_positions_all, axis=0)
avg_rl_positions = np.mean(rl_positions_all, axis=0)

plt.figure(figsize=(10, 5))

plt.plot(avg_delta_positions, label="Delta Hedging promedio")
plt.plot(avg_rl_positions, label="RL Hedging promedio")

plt.title("Hedge ratio promedio: Delta vs RL")
plt.xlabel("Tiempo")
plt.ylabel("Hedge ratio")
plt.legend()
plt.grid(True)
plt.show()

# 7. Interpretación automática simple

print("=== Interpretación inicial ===")

if rl_test_pnls.mean() > delta_test_pnls.mean():
    print("RL mejora el PnL promedio frente a Delta Hedging.")
else:
    print("Delta Hedging mantiene mejor PnL promedio que RL.")

if rl_test_pnls.std() < delta_test_pnls.std():
    print("RL reduce la volatilidad del PnL.")
else:
    print("RL presenta mayor dispersión del PnL.")

if np.percentile(rl_test_pnls, 5) > np.percentile(delta_test_pnls, 5):
    print("RL mejora el peor 5% de resultados.")
else:
    print("Delta Hedging protege mejor en el peor 5% de escenarios.")

"""# ============================================================
# PROYECTO 3 - BLOQUE 6: Reward robusto para reducir downside risk
# ============================================================
"""

# 1. Entorno robusto con penalización adicional por pérdidas y exceso de hedge

class RobustHedgingEnv(HedgingEnv):
    def __init__(
        self,
        S0, K, T, r, sigma, dt, transaction_cost,
        downside_penalty=3.0,
        position_penalty=0.02
    ):
        super().__init__(S0, K, T, r, sigma, dt, transaction_cost)
        self.downside_penalty = downside_penalty
        self.position_penalty = position_penalty

    def step(self, action):
        next_state, reward, done, info = super().step(action)

        position = info["position"]

        # Penaliza pérdidas más que ganancias
        if reward < 0:
            reward = reward - self.downside_penalty * reward**2

        # Penaliza posiciones demasiado altas
        reward = reward - self.position_penalty * position**2

        return next_state, reward, done, info

# 2. Crear entorno robusto

robust_env = RobustHedgingEnv(
    S0=S0,
    K=K,
    T=T,
    r=r,
    sigma=sigma,
    dt=dt,
    transaction_cost=transaction_cost,
    downside_penalty=3.0,
    position_penalty=0.02
)

# 3. Entrenar nueva política robusta

robust_policy = HedgePolicy()
robust_optimizer = optim.Adam(robust_policy.parameters(), lr=0.001)

robust_episode_rewards = []

n_episodes = 1000
gamma = 0.99

for episode in range(n_episodes):
    states, actions, rewards = run_episode(robust_env, robust_policy)
    discounted_rewards = compute_discounted_rewards(rewards, gamma=gamma)

    loss = 0

    for state_tensor, action, Gt in zip(states, actions, discounted_rewards):
        action_pred = robust_policy(state_tensor)
        loss += ((action_pred - action.detach()) ** 2 * (-Gt)).mean()

    robust_optimizer.zero_grad()
    loss.backward()
    robust_optimizer.step()

    robust_episode_rewards.append(sum(rewards))

    if episode % 100 == 0:
        print(f"Episode {episode}, Robust Reward: {sum(rewards):.4f}")

# 4. Graficar entrenamiento robusto

plt.figure(figsize=(10, 5))

plt.plot(pd.Series(episode_rewards).rolling(50).mean(), label="RL original")
plt.plot(pd.Series(robust_episode_rewards).rolling(50).mean(), label="RL robusto")

plt.title("Reward promedio móvil: RL original vs RL robusto")
plt.xlabel("Episodio")
plt.ylabel("Reward")
plt.legend()
plt.grid(True)
plt.show()

# 5. Evaluar RL robusto en test

robust_rl_test_pnls = []
robust_rl_positions_all = []

for i in range(n_test_paths):
    robust_pnl, robust_positions = rl_hedging_path(
        test_paths[:, i],
        robust_policy,
        K,
        T,
        r,
        sigma,
        dt,
        transaction_cost
    )

    robust_rl_test_pnls.append(robust_pnl)
    robust_rl_positions_all.append(robust_positions)

robust_rl_test_pnls = np.array(robust_rl_test_pnls)

# 6. Comparación final: Delta vs RL original vs RL robusto

comparison_robust = pd.DataFrame({
    "Metric": [
        "Average PnL",
        "Median PnL",
        "PnL Std",
        "5% Worst PnL",
        "95% Best PnL"
    ],
    "Delta Hedging": [
        delta_test_pnls.mean(),
        np.median(delta_test_pnls),
        delta_test_pnls.std(),
        np.percentile(delta_test_pnls, 5),
        np.percentile(delta_test_pnls, 95)
    ],
    "RL Original": [
        rl_test_pnls.mean(),
        np.median(rl_test_pnls),
        rl_test_pnls.std(),
        np.percentile(rl_test_pnls, 5),
        np.percentile(rl_test_pnls, 95)
    ],
    "RL Robusto": [
        robust_rl_test_pnls.mean(),
        np.median(robust_rl_test_pnls),
        robust_rl_test_pnls.std(),
        np.percentile(robust_rl_test_pnls, 5),
        np.percentile(robust_rl_test_pnls, 95)
    ]
})

display(comparison_robust)

# 7. Histograma comparativo

plt.figure(figsize=(10, 5))

plt.hist(delta_test_pnls, bins=40, alpha=0.5, label="Delta Hedging")
plt.hist(rl_test_pnls, bins=40, alpha=0.5, label="RL Original")
plt.hist(robust_rl_test_pnls, bins=40, alpha=0.5, label="RL Robusto")

plt.title("Distribución de PnL: Delta vs RL Original vs RL Robusto")
plt.xlabel("PnL final")
plt.ylabel("Frecuencia")
plt.legend()
plt.grid(True)
plt.show()

# 8. Política aprendida robusta vs Delta BSM

robust_rl_actions = []

robust_policy.eval()

for m in moneyness_grid:
    state = torch.tensor([[m, tau_fixed, 0.5]], dtype=torch.float32)

    with torch.no_grad():
        robust_action = robust_policy(state).item()

    robust_rl_actions.append(robust_action)

plt.figure(figsize=(10, 5))

plt.plot(moneyness_grid, bsm_deltas, label="Delta BSM")
plt.plot(moneyness_grid, rl_actions, label="RL Original")
plt.plot(moneyness_grid, robust_rl_actions, label="RL Robusto")

plt.title("Política aprendida: Delta vs RL Original vs RL Robusto")
plt.xlabel("Moneyness S/K")
plt.ylabel("Hedge Ratio")
plt.legend()
plt.grid(True)
plt.show()

"""# ============================================================
# PROYECTO 3 - BLOQUE 7: Reward extendido tipo hedge risk / CVaR
# ============================================================
"""

# 1. Entorno extendido: penaliza pérdidas, costos, exceso de posición
# y desviación frente a Delta BSM

class ExtendedHedgingEnv(HedgingEnv):
    def __init__(
        self,
        S0, K, T, r, sigma, dt, transaction_cost,
        downside_penalty=5.0,
        position_penalty=0.01,
        delta_tracking_penalty=0.10
    ):
        super().__init__(S0, K, T, r, sigma, dt, transaction_cost)
        self.downside_penalty = downside_penalty
        self.position_penalty = position_penalty
        self.delta_tracking_penalty = delta_tracking_penalty

    def step(self, action):
        next_state, reward, done, info = super().step(action)

        S = info["S"]
        tau = max(self.T - self.t * self.dt, 0)
        position = info["position"]

        delta_bsm = bs_delta(S, self.K, tau, self.r, self.sigma)

        # Penalización asimétrica por pérdidas
        if reward < 0:
            reward = reward - self.downside_penalty * reward**2

        # Penalización por exceso de posición
        reward = reward - self.position_penalty * position**2

        # Penalización por alejarse demasiado de Delta BSM
        reward = reward - self.delta_tracking_penalty * (position - delta_bsm)**2

        return next_state, reward, done, info

# 2. Crear entorno extendido

extended_env = ExtendedHedgingEnv(
    S0=S0,
    K=K,
    T=T,
    r=r,
    sigma=sigma,
    dt=dt,
    transaction_cost=transaction_cost,
    downside_penalty=5.0,
    position_penalty=0.01,
    delta_tracking_penalty=0.10
)

# 3. Entrenar política extendida

extended_policy = HedgePolicy()
extended_optimizer = optim.Adam(extended_policy.parameters(), lr=0.001)

extended_episode_rewards = []

n_episodes = 1500
gamma = 0.99

for episode in range(n_episodes):
    states, actions, rewards = run_episode(extended_env, extended_policy)
    discounted_rewards = compute_discounted_rewards(rewards, gamma=gamma)

    loss = 0

    for state_tensor, action, Gt in zip(states, actions, discounted_rewards):
        action_pred = extended_policy(state_tensor)
        loss += ((action_pred - action.detach()) ** 2 * (-Gt)).mean()

    extended_optimizer.zero_grad()
    loss.backward()
    extended_optimizer.step()

    extended_episode_rewards.append(sum(rewards))

    if episode % 150 == 0:
        print(f"Episode {episode}, Extended Reward: {sum(rewards):.4f}")

# 4. Evaluar RL extendido en test

extended_rl_test_pnls = []
extended_rl_positions_all = []

for i in range(n_test_paths):
    extended_pnl, extended_positions = rl_hedging_path(
        test_paths[:, i],
        extended_policy,
        K,
        T,
        r,
        sigma,
        dt,
        transaction_cost
    )

    extended_rl_test_pnls.append(extended_pnl)
    extended_rl_positions_all.append(extended_positions)

extended_rl_test_pnls = np.array(extended_rl_test_pnls)

# 5. Comparación final extendida

comparison_extended = pd.DataFrame({
    "Metric": [
        "Average PnL",
        "Median PnL",
        "PnL Std",
        "5% Worst PnL",
        "95% Best PnL"
    ],
    "Delta Hedging": [
        delta_test_pnls.mean(),
        np.median(delta_test_pnls),
        delta_test_pnls.std(),
        np.percentile(delta_test_pnls, 5),
        np.percentile(delta_test_pnls, 95)
    ],
    "RL Original": [
        rl_test_pnls.mean(),
        np.median(rl_test_pnls),
        rl_test_pnls.std(),
        np.percentile(rl_test_pnls, 5),
        np.percentile(rl_test_pnls, 95)
    ],
    "RL Robusto": [
        robust_rl_test_pnls.mean(),
        np.median(robust_rl_test_pnls),
        robust_rl_test_pnls.std(),
        np.percentile(robust_rl_test_pnls, 5),
        np.percentile(robust_rl_test_pnls, 95)
    ],
    "RL Extendido": [
        extended_rl_test_pnls.mean(),
        np.median(extended_rl_test_pnls),
        extended_rl_test_pnls.std(),
        np.percentile(extended_rl_test_pnls, 5),
        np.percentile(extended_rl_test_pnls, 95)
    ]
})

display(comparison_extended)

# 6. Histograma final

plt.figure(figsize=(11, 5))

plt.hist(delta_test_pnls, bins=40, alpha=0.45, label="Delta Hedging")
plt.hist(rl_test_pnls, bins=40, alpha=0.45, label="RL Original")
plt.hist(robust_rl_test_pnls, bins=40, alpha=0.45, label="RL Robusto")
plt.hist(extended_rl_test_pnls, bins=40, alpha=0.45, label="RL Extendido")

plt.title("Distribución de PnL: Delta vs RL Original vs Robusto vs Extendido")
plt.xlabel("PnL final")
plt.ylabel("Frecuencia")
plt.legend()
plt.grid(True)
plt.show()

# 7. Política extendida vs Delta

extended_rl_actions = []

extended_policy.eval()

for m in moneyness_grid:
    state = torch.tensor([[m, tau_fixed, 0.5]], dtype=torch.float32)

    with torch.no_grad():
        extended_action = extended_policy(state).item()

    extended_rl_actions.append(extended_action)

plt.figure(figsize=(10, 5))

plt.plot(moneyness_grid, bsm_deltas, label="Delta BSM")
plt.plot(moneyness_grid, rl_actions, label="RL Original")
plt.plot(moneyness_grid, robust_rl_actions, label="RL Robusto")
plt.plot(moneyness_grid, extended_rl_actions, label="RL Extendido")

plt.title("Política aprendida: Delta vs RL")
plt.xlabel("Moneyness S/K")
plt.ylabel("Hedge Ratio")
plt.legend()
plt.grid(True)
plt.show()

# 8. Métricas adicionales de riesgo de cola

def tail_metrics(pnls):
    return {
        "Mean": np.mean(pnls),
        "Std": np.std(pnls),
        "VaR 5%": np.percentile(pnls, 5),
        "CVaR 5%": pnls[pnls <= np.percentile(pnls, 5)].mean(),
        "Prob PnL < 0": np.mean(pnls < 0)
    }

tail_comparison = pd.DataFrame({
    "Delta Hedging": tail_metrics(delta_test_pnls),
    "RL Original": tail_metrics(rl_test_pnls),
    "RL Robusto": tail_metrics(robust_rl_test_pnls),
    "RL Extendido": tail_metrics(extended_rl_test_pnls)
})

display(tail_comparison)