# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# Basket Trading con Bayesian Optimization

## 1. Descargar data
"""

# ============================================================
# PROYECTO 1: Basket Trading con acciones
# Etapa 1: Descarga de datos y gráfico inicial
# ============================================================

# 1. Instalar librerías necesarias
!pip install yfinance -q

# 2. Importar librerías

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 3. Definir activos del basket

tickers = ["AAPL", "MSFT", "GOOGL"]

start_date = "2018-01-01"
end_date = "2025-12-31"

# 4. Descargar precios ajustados

data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True
)

prices = data["Close"]

prices.head()

# 5. Revisar información básica

print("Dimensiones del dataset:", prices.shape)
print("\nPrimeras filas:")
display(prices.head())

print("\nÚltimas filas:")
display(prices.tail())

print("\nValores nulos por activo:")
print(prices.isna().sum())

# 6. Limpiar datos

prices = prices.dropna()

print("Dimensiones después de limpiar:", prices.shape)

# 7. Graficar precios históricos

plt.figure(figsize=(12, 6))

for ticker in tickers:
    plt.plot(prices.index, prices[ticker], label=ticker)

plt.title("Precios históricos ajustados")
plt.xlabel("Fecha")
plt.ylabel("Precio ajustado")
plt.legend()
plt.grid(True)
plt.show()

# 8. Normalizar precios para comparar evolución relativa

normalized_prices = prices / prices.iloc[0] * 100

plt.figure(figsize=(12, 6))

for ticker in tickers:
    plt.plot(normalized_prices.index, normalized_prices[ticker], label=ticker)

plt.title("Evolución normalizada de precios")
plt.xlabel("Fecha")
plt.ylabel("Índice base 100")
plt.legend()
plt.grid(True)
plt.show()

# 9. Calcular retornos diarios

returns = prices.pct_change().dropna()

returns.head()

# 10. Matriz de correlación de retornos

corr_matrix = returns.corr()

display(corr_matrix)

# 11. Visualizar correlación

plt.figure(figsize=(6, 5))
plt.imshow(corr_matrix, cmap="Blues")
plt.colorbar(label="Correlación")

plt.xticks(range(len(tickers)), tickers)
plt.yticks(range(len(tickers)), tickers)

plt.title("Matriz de correlación de retornos")
plt.show()

"""## 2. Test de Johansen"""

# ============================================================
# BLOQUE 2: Test de Johansen y spread cointegrado
# ============================================================

!pip install statsmodels -q

from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# 1. Usamos precios en logaritmos
# Esto es estándar porque trabajamos con relaciones proporcionales

log_prices = np.log(prices)

log_prices.head()

# 2. Aplicar test de Johansen

johansen_test = coint_johansen(
    log_prices,
    det_order=0,   # sin tendencia determinística
    k_ar_diff=1    # rezagos en diferencias
)

# 3. Revisar eigenvalues

print("Eigenvalues:")
print(johansen_test.eig)

# 4. Revisar estadístico Trace Test

trace_stat = johansen_test.lr1
critical_values = johansen_test.cvt

johansen_results = pd.DataFrame({
    "Trace Statistic": trace_stat,
    "Critical Value 90%": critical_values[:, 0],
    "Critical Value 95%": critical_values[:, 1],
    "Critical Value 99%": critical_values[:, 2]
})

display(johansen_results)

# 5. Extraer el primer vector cointegrante
# Este vector nos da los pesos iniciales del basket

weights = johansen_test.evec[:, 0]

weights_df = pd.DataFrame({
    "Ticker": tickers,
    "Johansen Weight": weights
})

display(weights_df)

# 6. Normalizar pesos para interpretarlos mejor

weights_normalized = weights / np.sum(np.abs(weights))

weights_norm_df = pd.DataFrame({
    "Ticker": tickers,
    "Normalized Weight": weights_normalized
})

display(weights_norm_df)

# 7. Construir el spread cointegrado

spread = log_prices @ weights_normalized

spread.name = "Johansen Spread"

spread.head()

# 8. Graficar el spread

plt.figure(figsize=(12, 5))
plt.plot(spread.index, spread)
plt.title("Spread cointegrado - Johansen")
plt.xlabel("Fecha")
plt.ylabel("Spread")
plt.grid(True)
plt.show()

# 9. Calcular z-score del spread

spread_mean = spread.mean()
spread_std = spread.std()

zscore = (spread - spread_mean) / spread_std

zscore.name = "Z-Score"

zscore.head()

# 10. Graficar z-score con bandas de entrada y salida

plt.figure(figsize=(12, 5))
plt.plot(zscore.index, zscore, label="Z-Score")

plt.axhline(2, linestyle="--", label="Entrada Short Spread (+2)")
plt.axhline(-2, linestyle="--", label="Entrada Long Spread (-2)")
plt.axhline(0, linestyle="-", label="Media / Salida")

plt.title("Z-Score del Spread Cointegrado")
plt.xlabel("Fecha")
plt.ylabel("Z-Score")
plt.legend()
plt.grid(True)
plt.show()

"""## 3. Señales de trading y backtest baseline Johansen

"""

# 1. Parámetros de trading

entry_threshold = 2.0
exit_threshold = 0.0

# 2. Crear señales según el z-score

signals = pd.DataFrame(index=zscore.index)
signals["zscore"] = zscore
signals["position"] = 0

current_position = 0

for i in range(len(signals)):
    z = signals["zscore"].iloc[i]

    if current_position == 0:
        if z > entry_threshold:
            current_position = -1   # short spread
        elif z < -entry_threshold:
            current_position = 1    # long spread

    elif current_position == 1:
        if z >= exit_threshold:
            current_position = 0

    elif current_position == -1:
        if z <= exit_threshold:
            current_position = 0

    signals.iloc[i, signals.columns.get_loc("position")] = current_position

signals.head()

# 3. Graficar posición de la estrategia

plt.figure(figsize=(12, 4))
plt.plot(signals.index, signals["position"])

plt.title("Posición de la estrategia Johansen baseline")
plt.xlabel("Fecha")
plt.ylabel("Posición: 1 Long Spread, -1 Short Spread, 0 Sin posición")
plt.grid(True)
plt.show()

# 4. Retornos diarios de los activos

asset_returns = log_prices.diff().dropna()
asset_returns.head()

# 5. Retorno diario del spread/basket

basket_returns = asset_returns @ weights_normalized
basket_returns.name = "Basket Return"

basket_returns.head()

# 6. Alinear señales con retornos
# Usamos position.shift(1) para evitar look-ahead bias:
# la señal de hoy se ejecuta al siguiente día.

strategy_returns = signals["position"].shift(1) * basket_returns
strategy_returns = strategy_returns.dropna()

strategy_returns.name = "Strategy Return"

strategy_returns.head()

# 7. Curva acumulada de la estrategia

cumulative_returns = (1 + strategy_returns).cumprod()

plt.figure(figsize=(12, 5))
plt.plot(cumulative_returns.index, cumulative_returns)

plt.title("Backtest Johansen baseline - Retorno acumulado")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.grid(True)
plt.show()

# 8. Métricas básicas de performance

annual_factor = 252

mean_daily_return = strategy_returns.mean()
daily_volatility = strategy_returns.std()

annual_return = mean_daily_return * annual_factor
annual_volatility = daily_volatility * np.sqrt(annual_factor)

sharpe_ratio = annual_return / annual_volatility

running_max = cumulative_returns.cummax()
drawdown = cumulative_returns / running_max - 1
max_drawdown = drawdown.min()

performance_summary = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Value": [
        annual_return,
        annual_volatility,
        sharpe_ratio,
        max_drawdown,
        cumulative_returns.iloc[-1] - 1
    ]
})

display(performance_summary)

# 9. Graficar drawdown

plt.figure(figsize=(12, 4))
plt.plot(drawdown.index, drawdown)

plt.title("Drawdown - Johansen baseline")
plt.xlabel("Fecha")
plt.ylabel("Drawdown")
plt.grid(True)
plt.show()

# 10. Contar número de días en posición

position_summary = signals["position"].value_counts().sort_index()

display(position_summary)

"""## 4. Métricas ampliadas y análisis de trades

"""

# 1. Tabla de métricas con formato porcentual

performance_summary_formatted = performance_summary.copy()

percent_metrics = [
    "Annual Return",
    "Annual Volatility",
    "Max Drawdown",
    "Total Return"
]

performance_summary_formatted["Value"] = performance_summary_formatted.apply(
    lambda row: f"{row['Value']:.2%}" if row["Metric"] in percent_metrics else f"{row['Value']:.2f}",
    axis=1
)

display(performance_summary_formatted)

# 2. Calcular profit factor

positive_returns = strategy_returns[strategy_returns > 0].sum()
negative_returns = strategy_returns[strategy_returns < 0].sum()

profit_factor = positive_returns / abs(negative_returns)

print("Profit Factor:", round(profit_factor, 2))

# 3. Calcular win rate diario

winning_days = (strategy_returns > 0).sum()
losing_days = (strategy_returns < 0).sum()

win_rate = winning_days / (winning_days + losing_days)

print("Win Rate diario:", f"{win_rate:.2%}")

# 4. Identificar cambios de posición

signals["position_change"] = signals["position"].diff().fillna(0)

trade_events = signals[signals["position_change"] != 0]

display(trade_events.head(20))

# 5. Contar número aproximado de entradas

entries = trade_events[trade_events["position"] != 0]

print("Número de entradas:", len(entries))

# 6. Retorno acumulado por año

strategy_returns_by_year = strategy_returns.groupby(strategy_returns.index.year).apply(
    lambda x: (1 + x).prod() - 1
)

strategy_returns_by_year = strategy_returns_by_year.to_frame("Annual Strategy Return")

display(strategy_returns_by_year)

# 7. Gráfico de retornos anuales

plt.figure(figsize=(10, 5))
plt.bar(strategy_returns_by_year.index, strategy_returns_by_year["Annual Strategy Return"])

plt.title("Retorno anual de la estrategia Johansen baseline")
plt.xlabel("Año")
plt.ylabel("Retorno anual")
plt.grid(True)
plt.show()

# 8. Exposición promedio de la estrategia

average_exposure = signals["position"].abs().mean()

print("Exposición promedio:", f"{average_exposure:.2%}")

# 9. Días con posición activa

active_days = (signals["position"] != 0).sum()
total_days = len(signals)

print("Días con posición activa:", active_days)
print("Total de días:", total_days)
print("Porcentaje del tiempo invertido:", f"{active_days / total_days:.2%}")

"""## 5. Bayesian Optimization con Optuna
Objetivo: encontrar pesos que maximicen el Sharpe Ratio
"""

# 1. Instalar Optuna

!pip install optuna -q

# 2. Importar librerías

import optuna

# 3. Función para backtestear cualquier combinación de pesos

def backtest_basket(weights_array, log_prices, entry_threshold=2.0, exit_threshold=0.0):

    weights_array = np.array(weights_array)
    weights_array = weights_array / np.sum(np.abs(weights_array))

    spread_temp = log_prices @ weights_array

    z_temp = (spread_temp - spread_temp.mean()) / spread_temp.std()

    signals_temp = pd.DataFrame(index=z_temp.index)
    signals_temp["zscore"] = z_temp
    signals_temp["position"] = 0

    current_position = 0

    for i in range(len(signals_temp)):
        z = signals_temp["zscore"].iloc[i]

        if current_position == 0:
            if z > entry_threshold:
                current_position = -1
            elif z < -entry_threshold:
                current_position = 1

        elif current_position == 1:
            if z >= exit_threshold:
                current_position = 0

        elif current_position == -1:
            if z <= exit_threshold:
                current_position = 0

        signals_temp.iloc[i, signals_temp.columns.get_loc("position")] = current_position

    asset_returns_temp = log_prices.diff().dropna()
    basket_returns_temp = asset_returns_temp @ weights_array

    strategy_returns_temp = signals_temp["position"].shift(1) * basket_returns_temp
    strategy_returns_temp = strategy_returns_temp.dropna()

    if strategy_returns_temp.std() == 0:
        return None, None, None

    annual_return_temp = strategy_returns_temp.mean() * 252
    annual_vol_temp = strategy_returns_temp.std() * np.sqrt(252)
    sharpe_temp = annual_return_temp / annual_vol_temp

    cumulative_temp = (1 + strategy_returns_temp).cumprod()
    drawdown_temp = cumulative_temp / cumulative_temp.cummax() - 1
    max_drawdown_temp = drawdown_temp.min()

    return sharpe_temp, strategy_returns_temp, max_drawdown_temp

# 4. Definir función objetivo para Optuna

def objective(trial):

    w1 = trial.suggest_float("w_AAPL", -1, 1)
    w2 = trial.suggest_float("w_MSFT", -1, 1)
    w3 = trial.suggest_float("w_GOOGL", -1, 1)

    weights_trial = [w1, w2, w3]

    sharpe, strategy_returns_trial, max_drawdown = backtest_basket(
        weights_trial,
        log_prices,
        entry_threshold=2.0,
        exit_threshold=0.0
    )

    if sharpe is None:
        return -999

    return sharpe

# 5. Ejecutar Bayesian Optimization

study = optuna.create_study(direction="maximize")

study.optimize(objective, n_trials=200)

# 6. Ver mejores pesos encontrados

best_params = study.best_params
best_sharpe = study.best_value

print("Mejores parámetros:")
print(best_params)

print("\nMejor Sharpe encontrado:")
print(round(best_sharpe, 4))

# 7. Convertir mejores pesos a array normalizado

bo_weights = np.array([
    best_params["w_AAPL"],
    best_params["w_MSFT"],
    best_params["w_GOOGL"]
])

bo_weights_normalized = bo_weights / np.sum(np.abs(bo_weights))

bo_weights_df = pd.DataFrame({
    "Ticker": tickers,
    "BO Weight": bo_weights_normalized
})

display(bo_weights_df)

# 8. Backtest final con pesos optimizados

bo_sharpe, bo_strategy_returns, bo_max_drawdown = backtest_basket(
    bo_weights_normalized,
    log_prices,
    entry_threshold=2.0,
    exit_threshold=0.0
)

bo_cumulative_returns = (1 + bo_strategy_returns).cumprod()

# 9. Comparar Johansen vs Bayesian Optimization

plt.figure(figsize=(12, 5))

plt.plot(cumulative_returns.index, cumulative_returns, label="Johansen Baseline")
plt.plot(bo_cumulative_returns.index, bo_cumulative_returns, label="Bayesian Optimization")

plt.title("Comparación de retornos acumulados")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 10. Métricas comparativas

def calculate_metrics(strategy_returns):

    cumulative = (1 + strategy_returns).cumprod()

    annual_return = strategy_returns.mean() * 252
    annual_volatility = strategy_returns.std() * np.sqrt(252)
    sharpe = annual_return / annual_volatility

    drawdown = cumulative / cumulative.cummax() - 1
    max_drawdown = drawdown.min()

    total_return = cumulative.iloc[-1] - 1

    return annual_return, annual_volatility, sharpe, max_drawdown, total_return

johansen_metrics = calculate_metrics(strategy_returns)
bo_metrics = calculate_metrics(bo_strategy_returns)

comparison_df = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Johansen Baseline": johansen_metrics,
    "Bayesian Optimization": bo_metrics
})

display(comparison_df)

# 11. Tabla con formato más legible

comparison_formatted = comparison_df.copy()

for col in ["Johansen Baseline", "Bayesian Optimization"]:
    comparison_formatted[col] = comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(comparison_formatted)

bo_spread = log_prices @ bo_weights_normalized
bo_zscore = (bo_spread - bo_spread.mean()) / bo_spread.std()

plt.figure(figsize=(12, 5))
plt.plot(bo_zscore.index, bo_zscore, label="BO Z-Score")

plt.axhline(2, linestyle="--", label="+2")
plt.axhline(-2, linestyle="--", label="-2")
plt.axhline(0, linestyle="-", label="Media")

plt.title("Z-Score del spread optimizado con Bayesian Optimization")
plt.xlabel("Fecha")
plt.ylabel("Z-Score")
plt.legend()
plt.grid(True)
plt.show()

"""## 6. Validación Train/Test
Objetivo: comparar Johansen vs BO fuera de muestra

"""

# 1. Definir muestra de entrenamiento y prueba

split_date = "2022-01-01"

log_prices_train = log_prices[log_prices.index < split_date]
log_prices_test = log_prices[log_prices.index >= split_date]

print("Train:", log_prices_train.index.min(), "a", log_prices_train.index.max())
print("Test:", log_prices_test.index.min(), "a", log_prices_test.index.max())

# 2. Johansen solo con datos de entrenamiento

johansen_train = coint_johansen(
    log_prices_train,
    det_order=0,
    k_ar_diff=1
)

johansen_train_weights = johansen_train.evec[:, 0]
johansen_train_weights = johansen_train_weights / np.sum(np.abs(johansen_train_weights))

johansen_train_weights_df = pd.DataFrame({
    "Ticker": tickers,
    "Johansen Train Weight": johansen_train_weights
})

display(johansen_train_weights_df)

# 3. Optimizar BO usando SOLO entrenamiento

def objective_train(trial):

    w1 = trial.suggest_float("w_AAPL", -1, 1)
    w2 = trial.suggest_float("w_MSFT", -1, 1)
    w3 = trial.suggest_float("w_GOOGL", -1, 1)

    weights_trial = [w1, w2, w3]

    sharpe, _, _ = backtest_basket(
        weights_trial,
        log_prices_train,
        entry_threshold=2.0,
        exit_threshold=0.0
    )

    if sharpe is None:
        return -999

    return sharpe

study_train = optuna.create_study(direction="maximize")
study_train.optimize(objective_train, n_trials=200)

best_train_params = study_train.best_params

bo_train_weights = np.array([
    best_train_params["w_AAPL"],
    best_train_params["w_MSFT"],
    best_train_params["w_GOOGL"]
])

bo_train_weights = bo_train_weights / np.sum(np.abs(bo_train_weights))

bo_train_weights_df = pd.DataFrame({
    "Ticker": tickers,
    "BO Train Weight": bo_train_weights
})

display(bo_train_weights_df)

print("Best train Sharpe:", round(study_train.best_value, 4))

# 4. Backtest en TRAIN

johansen_train_sharpe, johansen_train_returns, johansen_train_dd = backtest_basket(
    johansen_train_weights,
    log_prices_train,
    entry_threshold=2.0,
    exit_threshold=0.0
)

bo_train_sharpe, bo_train_returns, bo_train_dd = backtest_basket(
    bo_train_weights,
    log_prices_train,
    entry_threshold=2.0,
    exit_threshold=0.0
)

# 5. Backtest en TEST usando pesos aprendidos en TRAIN

johansen_test_sharpe, johansen_test_returns, johansen_test_dd = backtest_basket(
    johansen_train_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0
)

bo_test_sharpe, bo_test_returns, bo_test_dd = backtest_basket(
    bo_train_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0
)

# 6. Comparar métricas train/test

metrics_train_test = pd.DataFrame({
    "Modelo": ["Johansen", "Bayesian Optimization"],
    "Sharpe Train": [johansen_train_sharpe, bo_train_sharpe],
    "Max DD Train": [johansen_train_dd, bo_train_dd],
    "Sharpe Test": [johansen_test_sharpe, bo_test_sharpe],
    "Max DD Test": [johansen_test_dd, bo_test_dd]
})

display(metrics_train_test)

# 7. Graficar curvas acumuladas en TEST

johansen_test_cum = (1 + johansen_test_returns).cumprod()
bo_test_cum = (1 + bo_test_returns).cumprod()

plt.figure(figsize=(12, 5))

plt.plot(johansen_test_cum.index, johansen_test_cum, label="Johansen Test")
plt.plot(bo_test_cum.index, bo_test_cum, label="BO Test")

plt.title("Performance fuera de muestra: Johansen vs BO")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 8. Tabla final con formato

metrics_train_test_formatted = metrics_train_test.copy()

for col in ["Max DD Train", "Max DD Test"]:
    metrics_train_test_formatted[col] = metrics_train_test_formatted[col].apply(lambda x: f"{x:.2%}")

for col in ["Sharpe Train", "Sharpe Test"]:
    metrics_train_test_formatted[col] = metrics_train_test_formatted[col].apply(lambda x: f"{x:.2f}")

display(metrics_train_test_formatted)

"""## 7. Rolling Window Backtest
Objetivo: reestimar pesos en ventanas móviles y evaluar OOS
"""

# 1. Parámetros del rolling window

train_window = 252 * 3   # 3 años de entrenamiento
test_window = 63         # 3 meses de prueba aprox.
step_size = 63           # avanzamos cada 3 meses

entry_threshold = 2.0
exit_threshold = 0.0

# 2. Función auxiliar para optimizar BO en una ventana

def optimize_bo_weights(log_prices_window, n_trials=100):

    def objective_window(trial):
        weights_trial = [
            trial.suggest_float("w1", -1, 1),
            trial.suggest_float("w2", -1, 1),
            trial.suggest_float("w3", -1, 1)
        ]

        sharpe, _, _ = backtest_basket(
            weights_trial,
            log_prices_window,
            entry_threshold=entry_threshold,
            exit_threshold=exit_threshold
        )

        if sharpe is None:
            return -999

        return sharpe

    study_window = optuna.create_study(direction="maximize")
    study_window.optimize(objective_window, n_trials=n_trials, show_progress_bar=False)

    best_weights = np.array([
        study_window.best_params["w1"],
        study_window.best_params["w2"],
        study_window.best_params["w3"]
    ])

    best_weights = best_weights / np.sum(np.abs(best_weights))

    return best_weights

# 3. Función auxiliar para pesos Johansen en una ventana

def get_johansen_weights(log_prices_window):

    johansen_window = coint_johansen(
        log_prices_window,
        det_order=0,
        k_ar_diff=1
    )

    weights_window = johansen_window.evec[:, 0]
    weights_window = weights_window / np.sum(np.abs(weights_window))

    return weights_window

# 4. Ejecutar rolling backtest

rolling_johansen_returns = []
rolling_bo_returns = []

rolling_dates = []
rolling_weights_johansen = []
rolling_weights_bo = []

for start in range(0, len(log_prices) - train_window - test_window, step_size):

    train_start = start
    train_end = start + train_window
    test_end = train_end + test_window

    train_data = log_prices.iloc[train_start:train_end]
    test_data = log_prices.iloc[train_end:test_end]

    try:
        # Johansen weights
        jw = get_johansen_weights(train_data)

        # BO weights
        bow = optimize_bo_weights(train_data, n_trials=100)

        # Test returns
        _, jr, _ = backtest_basket(
            jw,
            test_data,
            entry_threshold=entry_threshold,
            exit_threshold=exit_threshold
        )

        _, bor, _ = backtest_basket(
            bow,
            test_data,
            entry_threshold=entry_threshold,
            exit_threshold=exit_threshold
        )

        rolling_johansen_returns.append(jr)
        rolling_bo_returns.append(bor)

        rolling_dates.append(test_data.index[0])
        rolling_weights_johansen.append(jw)
        rolling_weights_bo.append(bow)

    except Exception as e:
        print("Error en ventana:", train_data.index[0], "-", train_data.index[-1], "|", e)

# 5. Unir retornos rolling

rolling_johansen_returns = pd.concat(rolling_johansen_returns).sort_index()
rolling_bo_returns = pd.concat(rolling_bo_returns).sort_index()

rolling_johansen_cum = (1 + rolling_johansen_returns).cumprod()
rolling_bo_cum = (1 + rolling_bo_returns).cumprod()

# 6. Graficar performance rolling out-of-sample

plt.figure(figsize=(12, 5))

plt.plot(rolling_johansen_cum.index, rolling_johansen_cum, label="Johansen Rolling OOS")
plt.plot(rolling_bo_cum.index, rolling_bo_cum, label="BO Rolling OOS")

plt.title("Rolling Window Out-of-Sample Performance")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 7. Métricas rolling OOS

rolling_johansen_metrics = calculate_metrics(rolling_johansen_returns)
rolling_bo_metrics = calculate_metrics(rolling_bo_returns)

rolling_comparison = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Johansen Rolling OOS": rolling_johansen_metrics,
    "BO Rolling OOS": rolling_bo_metrics
})

display(rolling_comparison)

# 8. Formato legible

rolling_comparison_formatted = rolling_comparison.copy()

for col in ["Johansen Rolling OOS", "BO Rolling OOS"]:
    rolling_comparison_formatted[col] = rolling_comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(rolling_comparison_formatted)

# 9. Ver evolución de pesos BO y Johansen

weights_bo_df = pd.DataFrame(
    rolling_weights_bo,
    index=rolling_dates,
    columns=[f"BO_{ticker}" for ticker in tickers]
)

weights_johansen_df = pd.DataFrame(
    rolling_weights_johansen,
    index=rolling_dates,
    columns=[f"Johansen_{ticker}" for ticker in tickers]
)

display(weights_bo_df.head())
display(weights_johansen_df.head())

# 10. Graficar evolución de pesos BO

plt.figure(figsize=(12, 5))

for col in weights_bo_df.columns:
    plt.plot(weights_bo_df.index, weights_bo_df[col], label=col)

plt.title("Evolución de pesos BO en rolling window")
plt.xlabel("Fecha")
plt.ylabel("Peso normalizado")
plt.legend()
plt.grid(True)
plt.show()

"""## 8. Bayesian Optimization con función objetivo robusta
Objetivo: maximizar Sharpe, penalizando drawdown y pocas operaciones

"""

# 1. Función para contar trades

def count_trades_from_returns(strategy_returns):
    active = strategy_returns != 0
    trade_starts = active & (~active.shift(1).fillna(False))
    return trade_starts.sum()

# 2. Backtest con métricas adicionales

def backtest_basket_extended(weights_array, log_prices, entry_threshold=2.0, exit_threshold=0.0):

    weights_array = np.array(weights_array)
    weights_array = weights_array / np.sum(np.abs(weights_array))

    spread_temp = log_prices @ weights_array
    z_temp = (spread_temp - spread_temp.mean()) / spread_temp.std()

    signals_temp = pd.DataFrame(index=z_temp.index)
    signals_temp["zscore"] = z_temp
    signals_temp["position"] = 0

    current_position = 0

    for i in range(len(signals_temp)):
        z = signals_temp["zscore"].iloc[i]

        if current_position == 0:
            if z > entry_threshold:
                current_position = -1
            elif z < -entry_threshold:
                current_position = 1

        elif current_position == 1:
            if z >= exit_threshold:
                current_position = 0

        elif current_position == -1:
            if z <= exit_threshold:
                current_position = 0

        signals_temp.iloc[i, signals_temp.columns.get_loc("position")] = current_position

    asset_returns_temp = log_prices.diff().dropna()
    basket_returns_temp = asset_returns_temp @ weights_array

    strategy_returns_temp = signals_temp["position"].shift(1) * basket_returns_temp
    strategy_returns_temp = strategy_returns_temp.dropna()

    if strategy_returns_temp.std() == 0:
        return None

    cumulative_temp = (1 + strategy_returns_temp).cumprod()
    drawdown_temp = cumulative_temp / cumulative_temp.cummax() - 1

    annual_return_temp = strategy_returns_temp.mean() * 252
    annual_vol_temp = strategy_returns_temp.std() * np.sqrt(252)
    sharpe_temp = annual_return_temp / annual_vol_temp
    max_drawdown_temp = drawdown_temp.min()

    trades_temp = count_trades_from_returns(strategy_returns_temp)

    return {
        "returns": strategy_returns_temp,
        "sharpe": sharpe_temp,
        "annual_return": annual_return_temp,
        "annual_volatility": annual_vol_temp,
        "max_drawdown": max_drawdown_temp,
        "total_return": cumulative_temp.iloc[-1] - 1,
        "trades": trades_temp
    }

# 3. Nueva función objetivo robusta

def robust_objective(trial):

    weights_trial = [
        trial.suggest_float("w1", -1, 1),
        trial.suggest_float("w2", -1, 1),
        trial.suggest_float("w3", -1, 1)
    ]

    result = backtest_basket_extended(
        weights_trial,
        log_prices_train,
        entry_threshold=2.0,
        exit_threshold=0.0
    )

    if result is None:
        return -999

    sharpe = result["sharpe"]
    max_drawdown = abs(result["max_drawdown"])
    trades = result["trades"]

    trade_penalty = 0

    if trades < 5:
        trade_penalty = 1.0

    score = sharpe - 2.0 * max_drawdown - trade_penalty

    return score

# 4. Optimizar con función robusta

robust_study = optuna.create_study(direction="maximize")
robust_study.optimize(robust_objective, n_trials=300)

print("Mejor score robusto:", round(robust_study.best_value, 4))
print("Mejores parámetros:", robust_study.best_params)

# 5. Pesos robustos normalizados

robust_weights = np.array([
    robust_study.best_params["w1"],
    robust_study.best_params["w2"],
    robust_study.best_params["w3"]
])

robust_weights = robust_weights / np.sum(np.abs(robust_weights))

robust_weights_df = pd.DataFrame({
    "Ticker": tickers,
    "Robust BO Weight": robust_weights
})

display(robust_weights_df)

# 6. Backtest robust BO en test

robust_test_result = backtest_basket_extended(
    robust_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0
)

robust_test_returns = robust_test_result["returns"]
robust_test_cum = (1 + robust_test_returns).cumprod()

# 7. Comparar Johansen, BO original y BO robusto en test

plt.figure(figsize=(12, 5))

plt.plot(johansen_test_cum.index, johansen_test_cum, label="Johansen Test")
plt.plot(bo_test_cum.index, bo_test_cum, label="BO Test")
plt.plot(robust_test_cum.index, robust_test_cum, label="Robust BO Test")

plt.title("Comparación fuera de muestra: Johansen vs BO vs Robust BO")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 8. Tabla comparativa final en test

robust_test_metrics = calculate_metrics(robust_test_returns)

test_comparison = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Johansen Test": johansen_metrics if False else calculate_metrics(johansen_test_returns),
    "BO Test": calculate_metrics(bo_test_returns),
    "Robust BO Test": robust_test_metrics
})

display(test_comparison)

# 9. Formato legible

test_comparison_formatted = test_comparison.copy()

for col in ["Johansen Test", "BO Test", "Robust BO Test"]:
    test_comparison_formatted[col] = test_comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(test_comparison_formatted)

"""## 9. Costos de transacción
Objetivo: hacer el backtest más realista
"""

# 1. Backtest extendido con costos de transacción

def backtest_basket_with_costs(
    weights_array,
    log_prices,
    entry_threshold=2.0,
    exit_threshold=0.0,
    transaction_cost=0.001  # 10 bps por cambio de posición
):

    weights_array = np.array(weights_array)
    weights_array = weights_array / np.sum(np.abs(weights_array))

    spread_temp = log_prices @ weights_array
    z_temp = (spread_temp - spread_temp.mean()) / spread_temp.std()

    signals_temp = pd.DataFrame(index=z_temp.index)
    signals_temp["zscore"] = z_temp
    signals_temp["position"] = 0

    current_position = 0

    for i in range(len(signals_temp)):
        z = signals_temp["zscore"].iloc[i]

        if current_position == 0:
            if z > entry_threshold:
                current_position = -1
            elif z < -entry_threshold:
                current_position = 1

        elif current_position == 1:
            if z >= exit_threshold:
                current_position = 0

        elif current_position == -1:
            if z <= exit_threshold:
                current_position = 0

        signals_temp.iloc[i, signals_temp.columns.get_loc("position")] = current_position

    asset_returns_temp = log_prices.diff().dropna()
    basket_returns_temp = asset_returns_temp @ weights_array

    gross_returns = signals_temp["position"].shift(1) * basket_returns_temp
    gross_returns = gross_returns.dropna()

    position_changes = signals_temp["position"].diff().abs()
    position_changes = position_changes.reindex(gross_returns.index).fillna(0)

    costs = position_changes * transaction_cost

    net_returns = gross_returns - costs
    net_returns.name = "Net Strategy Return"

    return net_returns, gross_returns, costs, signals_temp

# 2. Aplicar costos a Johansen, BO y Robust BO en test

transaction_cost = 0.001  # 10 bps

johansen_net_returns, johansen_gross_returns, johansen_costs, johansen_signals_cost = backtest_basket_with_costs(
    johansen_train_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0,
    transaction_cost=transaction_cost
)

bo_net_returns, bo_gross_returns, bo_costs, bo_signals_cost = backtest_basket_with_costs(
    bo_train_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0,
    transaction_cost=transaction_cost
)

robust_net_returns, robust_gross_returns, robust_costs, robust_signals_cost = backtest_basket_with_costs(
    robust_weights,
    log_prices_test,
    entry_threshold=2.0,
    exit_threshold=0.0,
    transaction_cost=transaction_cost
)

# 3. Curvas acumuladas netas

johansen_net_cum = (1 + johansen_net_returns).cumprod()
bo_net_cum = (1 + bo_net_returns).cumprod()
robust_net_cum = (1 + robust_net_returns).cumprod()

plt.figure(figsize=(12, 5))

plt.plot(johansen_net_cum.index, johansen_net_cum, label="Johansen Net")
plt.plot(bo_net_cum.index, bo_net_cum, label="BO Net")
plt.plot(robust_net_cum.index, robust_net_cum, label="Robust BO Net")

plt.title("Performance neta de costos - Test")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 4. Comparar gross vs net para Johansen

johansen_gross_cum = (1 + johansen_gross_returns).cumprod()

plt.figure(figsize=(12, 5))

plt.plot(johansen_gross_cum.index, johansen_gross_cum, label="Johansen Gross")
plt.plot(johansen_net_cum.index, johansen_net_cum, label="Johansen Net")

plt.title("Johansen: retorno bruto vs neto de costos")
plt.xlabel("Fecha")
plt.ylabel("Crecimiento de $1")
plt.legend()
plt.grid(True)
plt.show()

# 5. Métricas netas de costos

cost_comparison = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Johansen Net": calculate_metrics(johansen_net_returns),
    "BO Net": calculate_metrics(bo_net_returns),
    "Robust BO Net": calculate_metrics(robust_net_returns)
})

display(cost_comparison)

# 6. Formato legible

cost_comparison_formatted = cost_comparison.copy()

for col in ["Johansen Net", "BO Net", "Robust BO Net"]:
    cost_comparison_formatted[col] = cost_comparison_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(cost_comparison_formatted)

# 7. Costo total acumulado por estrategia

cost_summary = pd.DataFrame({
    "Strategy": ["Johansen", "BO", "Robust BO"],
    "Total Transaction Cost": [
        johansen_costs.sum(),
        bo_costs.sum(),
        robust_costs.sum()
    ]
})

display(cost_summary)

"""## 10. Resumen final del proyecto

"""

# 1. Consolidar métricas finales (netas de costos)

final_metrics = pd.DataFrame({
    "Metric": [
        "Annual Return",
        "Annual Volatility",
        "Sharpe Ratio",
        "Max Drawdown",
        "Total Return"
    ],
    "Johansen": calculate_metrics(johansen_net_returns),
    "BO": calculate_metrics(bo_net_returns),
    "Robust BO": calculate_metrics(robust_net_returns)
})

display(final_metrics)

# 2. Formato para presentación

final_metrics_formatted = final_metrics.copy()

for col in ["Johansen", "BO", "Robust BO"]:
    final_metrics_formatted[col] = final_metrics_formatted.apply(
        lambda row: f"{row[col]:.2%}" if row["Metric"] != "Sharpe Ratio" else f"{row[col]:.2f}",
        axis=1
    )

display(final_metrics_formatted)

print("=== INTERPRETACIÓN AUTOMÁTICA ===\n")

print("1. Johansen:")
print("- Estrategia basada en cointegración estadística.")
print("- Más estable out-of-sample.")
print("- Menor riesgo de sobreoptimización.\n")

print("2. Bayesian Optimization:")
print("- Maximiza performance en entrenamiento.")
print("- Puede generar mayores retornos in-sample.")
print("- Riesgo alto de sobreajuste.\n")

print("3. Robust BO:")
print("- Introduce penalización por riesgo y baja actividad.")
print("- Mejora disciplina del modelo.")
print("- No garantiza mejor performance fuera de muestra.\n")

