# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# 1. Obtener Datos
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ticker = "SPY"
start_date = "2005-01-01"
end_date = "2025-12-31"

data = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True)

# Flatten the MultiIndex columns to single-level strings and remove any name
data.columns = data.columns.get_level_values(0)
data.columns.name = None

data.head()

data["Return"] = data["Close"].pct_change()
data["Vol_21d"] = data["Return"].rolling(21).std() * np.sqrt(252)

data["Peak"] = data["Close"].cummax()
data["Drawdown"] = data["Close"] / data["Peak"] - 1

data = data.dropna()

data[["Close", "Return", "Vol_21d", "Drawdown"]].head()

"""# 2. K-Means"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

features = data[["Return", "Vol_21d", "Drawdown"]].copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
data["Regime"] = kmeans.fit_predict(X_scaled)

regime_names = {
    0: "Stress / Crisis",
    1: "Normal / Bullish",
    2: "Correction / Weak Market"
}

data["Regime_Name"] = data["Regime"].map(regime_names)

data[["Close", "Return", "Vol_21d", "Drawdown", "Regime", "Regime_Name"]].head()

regime_summary = data.groupby("Regime")[["Return", "Vol_21d", "Drawdown"]].mean()
regime_summary

plt.figure(figsize=(14, 6))

for regime in sorted(data["Regime"].unique()):
    subset = data[data["Regime"] == regime]
    plt.scatter(subset.index, subset["Close"], s=10, label=f"Regime {regime}")

plt.title("SPY - Market Regimes usando K-Means")
plt.xlabel("Fecha")
plt.ylabel("Precio")
plt.legend()
plt.grid(True)
plt.show()

data["Regime_Name"].value_counts(normalize=True).sort_values(ascending=False)

"""# 3. HMM"""

!pip install hmmlearn
from hmmlearn.hmm import GaussianHMM

returns = data["Return"].values.reshape(-1, 1)

hmm = GaussianHMM(
    n_components=3,        # 3 regímenes como KMeans
    covariance_type="full",
    n_iter=1000,
    random_state=42
)

hmm.fit(returns)

data["HMM_Regime"] = hmm.predict(returns)

data[["Return", "HMM_Regime"]].head()

hmm_summary = data.groupby("HMM_Regime")[["Return", "Vol_21d", "Drawdown"]].mean()
hmm_summary

plt.figure(figsize=(14,6))

for regime in sorted(data["HMM_Regime"].unique()):
    subset = data[data["HMM_Regime"] == regime]
    plt.scatter(subset.index, subset["Close"], s=10, label=f"HMM {regime}")

plt.title("SPY - Market Regimes usando HMM")
plt.xlabel("Fecha")
plt.ylabel("Precio")
plt.legend()
plt.grid(True)
plt.show()

"""# 4. Estrategia"""

data["Signal"] = (data["HMM_Regime"] == 0).astype(int)

data["Strategy_Return"] = data["Signal"].shift(1) * data["Return"]
data["BuyHold_Return"] = data["Return"]

data["Strategy_Cum"] = (1 + data["Strategy_Return"]).cumprod()
data["BuyHold_Cum"] = (1 + data["BuyHold_Return"]).cumprod()

plt.figure(figsize=(14,6))

plt.plot(data.index, data["Strategy_Cum"], label="HMM Strategy")
plt.plot(data.index, data["BuyHold_Cum"], label="Buy & Hold", alpha=0.7)

plt.title("Estrategia con filtro de régimen vs Buy & Hold")
plt.legend()
plt.grid(True)
plt.show()

"""# 5. Testeo"""

train = data.loc[: "2015-12-31"].copy()
test = data.loc["2016-01-01":].copy()

returns_train = train["Return"].values.reshape(-1, 1)
returns_test = test["Return"].values.reshape(-1, 1)

hmm_oos = GaussianHMM(
    n_components=3,
    covariance_type="full",
    n_iter=1000,
    random_state=42
)

hmm_oos.fit(returns_train)

test["HMM_Regime"] = hmm_oos.predict(returns_test)

test_summary = test.groupby("HMM_Regime")[["Return", "Vol_21d", "Drawdown"]].mean()
test_summary

regime_stats = test.groupby("HMM_Regime")["Return"].mean()
best_regime = regime_stats.idxmax()

best_regime

test["Signal"] = (test["HMM_Regime"] == best_regime).astype(int)

test["Strategy_Return"] = test["Signal"].shift(1) * test["Return"]
test["BuyHold_Return"] = test["Return"]

test = test.dropna()

test["Strategy_Cum"] = (1 + test["Strategy_Return"]).cumprod()
test["BuyHold_Cum"] = (1 + test["BuyHold_Return"]).cumprod()

plt.figure(figsize=(14,6))
plt.plot(test.index, test["Strategy_Cum"], label="HMM Strategy OOS")
plt.plot(test.index, test["BuyHold_Cum"], label="Buy & Hold", alpha=0.7)
plt.title("Out-of-Sample: HMM Strategy vs Buy & Hold")
plt.legend()
plt.grid(True)
plt.show()

"""# 6. Métricas comparables"""

def performance_metrics(returns, periods_per_year=252):
    returns = returns.dropna()

    cumulative_return = (1 + returns).prod() - 1
    years = len(returns) / periods_per_year
    cagr = (1 + cumulative_return) ** (1 / years) - 1

    volatility = returns.std() * np.sqrt(periods_per_year)
    sharpe = cagr / volatility

    cumulative = (1 + returns).cumprod()
    peak = cumulative.cummax()
    drawdown = cumulative / peak - 1
    max_drawdown = drawdown.min()

    return pd.Series({
        "Cumulative Return": cumulative_return,
        "CAGR": cagr,
        "Volatility": volatility,
        "Sharpe": sharpe,
        "Max Drawdown": max_drawdown
    })

metrics = pd.DataFrame({
    "HMM Strategy OOS": performance_metrics(test["Strategy_Return"]),
    "Buy & Hold": performance_metrics(test["BuyHold_Return"])
})

metrics

metrics_formatted = metrics.copy()

for row in ["Cumulative Return", "CAGR", "Volatility", "Max Drawdown"]:
    metrics_formatted.loc[row] = metrics_formatted.loc[row].map(lambda x: f"{x:.2%}")

metrics_formatted.loc["Sharpe"] = metrics.loc["Sharpe"].map(lambda x: f"{x:.2f}")

metrics_formatted

"""# 7. Costos de Transacción"""

# Detectar cambios de posición
test["Trade"] = test["Signal"].diff().abs()

# Costo por trade: ejemplo 0.10% por cambio de posición
transaction_cost = 0.001

test["Transaction_Cost"] = test["Trade"] * transaction_cost

test["Strategy_Return_Net"] = test["Strategy_Return"] - test["Transaction_Cost"]

test["Strategy_Cum_Net"] = (1 + test["Strategy_Return_Net"]).cumprod()

plt.figure(figsize=(14,6))

plt.plot(test.index, test["Strategy_Cum"], label="HMM Strategy Gross")
plt.plot(test.index, test["Strategy_Cum_Net"], label="HMM Strategy Net")
plt.plot(test.index, test["BuyHold_Cum"], label="Buy & Hold", alpha=0.7)

plt.title("HMM Strategy: Gross vs Net of Transaction Costs")
plt.legend()
plt.grid(True)
plt.show()

metrics_net = pd.DataFrame({
    "HMM Strategy Gross": performance_metrics(test["Strategy_Return"]),
    "HMM Strategy Net": performance_metrics(test["Strategy_Return_Net"]),
    "Buy & Hold": performance_metrics(test["BuyHold_Return"])
})

metrics_net

metrics_net_formatted = metrics_net.copy().astype(object)

for row in ["Cumulative Return", "CAGR", "Volatility", "Max Drawdown"]:
    metrics_net_formatted.loc[row] = metrics_net.loc[row].map(lambda x: f"{x:.2%}")

metrics_net_formatted.loc["Sharpe"] = metrics_net.loc["Sharpe"].map(lambda x: f"{x:.2f}")

metrics_net_formatted

"""# 8. Avoid Crisis Regimen"""

worst_regime = test.groupby("HMM_Regime")["Drawdown"].mean().idxmin()
worst_regime

test["Signal_Avoid"] = (test["HMM_Regime"] != worst_regime).astype(int)

test["Strategy_Return_Avoid"] = test["Signal_Avoid"].shift(1) * test["Return"]

test["Trade_Avoid"] = test["Signal_Avoid"].diff().abs()
test["Transaction_Cost_Avoid"] = test["Trade_Avoid"] * transaction_cost

test["Strategy_Return_Avoid_Net"] = test["Strategy_Return_Avoid"] - test["Transaction_Cost_Avoid"]

test["Strategy_Cum_Avoid"] = (1 + test["Strategy_Return_Avoid_Net"]).cumprod()

plt.figure(figsize=(14,6))

plt.plot(test.index, test["Strategy_Cum_Avoid"], label="Avoid Crisis Strategy")
plt.plot(test.index, test["Strategy_Cum_Net"], label="Best Regime Strategy")
plt.plot(test.index, test["BuyHold_Cum"], label="Buy & Hold", alpha=0.7)

plt.title("Estrategias: Avoid Crisis vs Best Regime vs Buy & Hold")
plt.legend()
plt.grid(True)
plt.show()

metrics_final = pd.DataFrame({
    "Avoid Crisis": performance_metrics(test["Strategy_Return_Avoid_Net"]),
    "Best Regime": performance_metrics(test["Strategy_Return_Net"]),
    "Buy & Hold": performance_metrics(test["BuyHold_Return"])
})

metrics_final