# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# 1. Descargar Options Chain
"""

import yfinance as yf
import pandas as pd
import numpy as np

ticker = "SPY"
spy = yf.Ticker(ticker)

expirations = spy.options
expirations[:10]

expiration = expirations[0]
expiration

opt_chain = spy.option_chain(expiration)

calls = opt_chain.calls
puts = opt_chain.puts

calls.head()

calls.columns

calls = calls[["strike", "lastPrice", "bid", "ask", "impliedVolatility"]].copy()

# eliminar datos raros
calls = calls[(calls["impliedVolatility"] > 0) & (calls["impliedVolatility"] < 5)]

calls.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(calls["strike"], calls["impliedVolatility"], marker="o")

plt.title(f"Volatility Smile - {expiration}")
plt.xlabel("Strike")
plt.ylabel("Implied Volatility")
plt.grid(True)
plt.show()

"""# 2. Black-Scholes"""

calls = opt_chain.calls.copy()

calls = calls[["strike", "lastPrice", "bid", "ask", "volume", "openInterest", "impliedVolatility"]]

calls["mid"] = (calls["bid"] + calls["ask"]) / 2
calls["spread"] = calls["ask"] - calls["bid"]

calls = calls[
    (calls["bid"] > 0) &
    (calls["ask"] > 0) &
    (calls["mid"] > 0) &
    (calls["spread"] / calls["mid"] < 0.30) &
    (calls["impliedVolatility"] > 0) &
    (calls["impliedVolatility"] < 2)
].copy()

calls.head()

from scipy.stats import norm
from scipy.optimize import brentq
import numpy as np

def black_scholes_call(S, K, T, r, sigma):
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    call_price = S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

    return call_price

def implied_vol_call(price, S, K, T, r):
    try:
        return brentq(
            lambda sigma: black_scholes_call(S, K, T, r, sigma) - price,
            0.0001,
            5.0
        )
    except:
        return np.nan

from datetime import datetime

S = spy.history(period="1d")["Close"].iloc[-1]
r = 0.05

expiration_date = datetime.strptime(expiration, "%Y-%m-%d")
today = datetime.today()

T = (expiration_date - today).days / 365

S, T

calls["iv_model"] = calls.apply(
    lambda row: implied_vol_call(
        price=row["mid"],
        S=S,
        K=row["strike"],
        T=T,
        r=r
    ),
    axis=1
)

calls[["strike", "mid", "impliedVolatility", "iv_model"]].head()

plt.figure(figsize=(10,6))

plt.plot(calls["strike"], calls["impliedVolatility"], marker="o", label="Yahoo IV")
plt.plot(calls["strike"], calls["iv_model"], marker="x", label="Model IV")

plt.title(f"Yahoo IV vs Black-Scholes Implied Vol - {expiration}")
plt.xlabel("Strike")
plt.ylabel("Implied Volatility")
plt.legend()
plt.grid(True)
plt.show()

"""# 3. Moneyness"""

S

calls_clean = calls.copy()

calls_clean["moneyness"] = calls_clean["strike"] / S

calls_clean = calls_clean[
    (calls_clean["moneyness"] > 0.85) &
    (calls_clean["moneyness"] < 1.15) &
    (calls_clean["iv_model"].notna())
].copy()

calls_clean[["strike", "mid", "moneyness", "impliedVolatility", "iv_model"]].head()

plt.figure(figsize=(10,6))

plt.plot(calls_clean["strike"], calls_clean["impliedVolatility"], marker="o", label="Yahoo IV")
plt.plot(calls_clean["strike"], calls_clean["iv_model"], marker="x", label="Model IV")

plt.title(f"Clean IV Smile - {expiration}")
plt.xlabel("Strike")
plt.ylabel("Implied Volatility")
plt.legend()
plt.grid(True)
plt.show()

"""# 4. Superficie de Volatilidad"""

surface_data = []

# usamos las primeras 8 expiraciones disponibles
for expiration in expirations[:8]:
    opt_chain = spy.option_chain(expiration)
    calls = opt_chain.calls.copy()

    calls = calls[["strike", "bid", "ask", "impliedVolatility"]]
    calls["mid"] = (calls["bid"] + calls["ask"]) / 2
    calls["spread"] = calls["ask"] - calls["bid"]

    expiration_date = datetime.strptime(expiration, "%Y-%m-%d")
    T = (expiration_date - datetime.today()).days / 365

    if T <= 0:
        continue

    calls = calls[
        (calls["bid"] > 0) &
        (calls["ask"] > 0) &
        (calls["mid"] > 0) &
        (calls["spread"] / calls["mid"] < 0.30)
    ].copy()

    calls["moneyness"] = calls["strike"] / S

    calls = calls[
        (calls["moneyness"] > 0.85) &
        (calls["moneyness"] < 1.15)
    ].copy()

    calls["expiration"] = expiration
    calls["T"] = T

    surface_data.append(calls)

surface = pd.concat(surface_data, ignore_index=True)

surface[["expiration", "T", "strike", "moneyness", "impliedVolatility"]].head()

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(
    surface["moneyness"],
    surface["T"],
    surface["impliedVolatility"],
    s=15
)

ax.set_title("Implied Volatility Surface - SPY")
ax.set_xlabel("Moneyness (K / S)")
ax.set_ylabel("Time to Expiry")
ax.set_zlabel("Implied Volatility")

plt.show()

plt.figure(figsize=(12, 6))

for expiration in surface["expiration"].unique():
    subset = surface[surface["expiration"] == expiration]
    plt.plot(
        subset["moneyness"],
        subset["impliedVolatility"],
        marker="o",
        label=expiration
    )

plt.title("Volatility Smile por Expiración")
plt.xlabel("Moneyness (K / S)")
plt.ylabel("Implied Volatility")
plt.legend()
plt.grid(True)
plt.show()

"""# 5 Suavizar la superficie"""

from scipy.interpolate import griddata

grid_x, grid_y = np.meshgrid(
    np.linspace(surface["moneyness"].min(), surface["moneyness"].max(), 50),
    np.linspace(surface["T"].min(), surface["T"].max(), 50)
)

grid_z = griddata(
    (surface["moneyness"], surface["T"]),
    surface["impliedVolatility"],
    (grid_x, grid_y),
    method="cubic"
)

fig = plt.figure(figsize=(12,8))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(grid_x, grid_y, grid_z, cmap='viridis')

ax.set_title("Smoothed Implied Vol Surface")
ax.set_xlabel("Moneyness")
ax.set_ylabel("Time to Expiry")
ax.set_zlabel("IV")

plt.show()