# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# 1. Data Multi Activo
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

tickers = ["SPY", "QQQ", "IWM", "TLT", "GLD", "EFA", "EEM"]

start_date = "2015-01-01"
end_date = "2025-12-31"

prices = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True
)["Close"]

prices.head()

returns = prices.pct_change().dropna()

returns.head()

summary = pd.DataFrame({
    "Annual Return": returns.mean() * 252,
    "Annual Volatility": returns.std() * np.sqrt(252),
    "Sharpe Approx": (returns.mean() * 252) / (returns.std() * np.sqrt(252))
})

summary

normalized_prices = prices / prices.iloc[0]

plt.figure(figsize=(14,6))
for ticker in tickers:
    plt.plot(normalized_prices.index, normalized_prices[ticker], label=ticker)

plt.title("Precios normalizados")
plt.legend()
plt.grid(True)
plt.show()

"""# 2. Portafolio Base"""

weights_eq = np.array([1/len(tickers)] * len(tickers))

portfolio_returns_eq = returns.dot(weights_eq)

portfolio_returns_eq.head()

cum_eq = (1 + portfolio_returns_eq).cumprod()

plt.figure(figsize=(14,6))
plt.plot(cum_eq.index, cum_eq, label="Equal Weight Portfolio")
plt.title("Portafolio Equal Weight")
plt.legend()
plt.grid(True)
plt.show()

def performance_metrics(returns, periods_per_year=252):
    returns = returns.dropna()

    cumulative_return = (1 + returns).prod() - 1
    years = len(returns) / periods_per_year
    cagr = (1 + cumulative_return) ** (1 / years) - 1

    volatility = returns.std() * np.sqrt(periods_per_year)
    sharpe = cagr / volatility

    cumulative = (1 + returns).cumprod()
    peak = cumulative.cummax()
    drawdown = cumulative / peak - 1
    max_drawdown = drawdown.min()

    return pd.Series({
        "Cumulative Return": cumulative_return,
        "CAGR": cagr,
        "Volatility": volatility,
        "Sharpe": sharpe,
        "Max Drawdown": max_drawdown
    })

metrics_eq = performance_metrics(portfolio_returns_eq)

metrics_eq

"""# 3. VaR y CVaR"""

alpha = 0.05  # peor 5% de retornos

VaR_eq = portfolio_returns_eq.quantile(alpha)

CVaR_eq = portfolio_returns_eq[portfolio_returns_eq <= VaR_eq].mean()

VaR_eq, CVaR_eq

print(f"VaR 95% diario: {VaR_eq:.2%}")
print(f"CVaR 95% diario: {CVaR_eq:.2%}")

plt.figure(figsize=(10,6))
plt.hist(portfolio_returns_eq, bins=60, alpha=0.7)

plt.axvline(VaR_eq, linestyle="--", label=f"VaR 95%: {VaR_eq:.2%}")
plt.axvline(CVaR_eq, linestyle="-", label=f"CVaR 95%: {CVaR_eq:.2%}")

plt.title("Distribución de retornos diarios - Equal Weight")
plt.xlabel("Retorno diario")
plt.ylabel("Frecuencia")
plt.legend()
plt.grid(True)
plt.show()

"""# 4. Optimizar CVaR"""

pip install cvxpy

import cvxpy as cp

R = returns.values
n_assets = R.shape[1]
n_obs = R.shape[0]

alpha = 0.05

w = cp.Variable(n_assets)
z = cp.Variable(1)
u = cp.Variable(n_obs)

portfolio_losses = -R @ w

objective = cp.Minimize(
    z + (1 / (alpha * n_obs)) * cp.sum(u)
)

constraints = [
    cp.sum(w) == 1,
    w >= 0,
    u >= 0,
    u >= portfolio_losses - z
]

problem = cp.Problem(objective, constraints)
problem.solve()

weights_cvar = pd.Series(w.value, index=returns.columns)

weights_cvar

portfolio_returns_cvar = returns.dot(weights_cvar)

metrics_cvar = pd.DataFrame({
    "Equal Weight": performance_metrics(portfolio_returns_eq),
    "CVaR Optimized": performance_metrics(portfolio_returns_cvar)
})

metrics_cvar

cum_cvar = (1 + portfolio_returns_cvar).cumprod()

plt.figure(figsize=(14,6))
plt.plot(cum_eq.index, cum_eq, label="Equal Weight")
plt.plot(cum_cvar.index, cum_cvar, label="CVaR Optimized")
plt.title("Equal Weight vs CVaR Optimized Portfolio")
plt.legend()
plt.grid(True)
plt.show()

"""# 5. CVaR con Retonro Mínimo"""

target_return = 0.10  # 10% anual

mu = returns.mean().values * 252

w = cp.Variable(n_assets)
z = cp.Variable(1)
u = cp.Variable(n_obs)

portfolio_losses = -R @ w

objective = cp.Minimize(
    z + (1 / (alpha * n_obs)) * cp.sum(u)
)

constraints = [
    cp.sum(w) == 1,
    w >= 0,
    u >= 0,
    u >= portfolio_losses - z,
    mu @ w >= target_return
]

problem = cp.Problem(objective, constraints)
problem.solve()

weights_cvar_target = pd.Series(w.value, index=returns.columns)
weights_cvar_target

portfolio_returns_cvar_target = returns.dot(weights_cvar_target)

metrics_target = pd.DataFrame({
    "Equal Weight": performance_metrics(portfolio_returns_eq),
    "CVaR Min": performance_metrics(portfolio_returns_cvar),
    "CVaR + Target Return": performance_metrics(portfolio_returns_cvar_target)
})

metrics_target

cum_target = (1 + portfolio_returns_cvar_target).cumprod()

plt.figure(figsize=(14,6))
plt.plot(cum_eq.index, cum_eq, label="Equal Weight")
plt.plot(cum_cvar.index, cum_cvar, label="CVaR Min")
plt.plot(cum_target.index, cum_target, label="CVaR + Target Return")

plt.title("Portafolios: Equal Weight vs CVaR")
plt.legend()
plt.grid(True)
plt.show()

"""# 6. Resultados"""

def var_cvar(returns, alpha=0.05):
    var = returns.quantile(alpha)
    cvar = returns[returns <= var].mean()
    return pd.Series({
        "VaR 95% diario": var,
        "CVaR 95% diario": cvar
    })

risk_tail = pd.DataFrame({
    "Equal Weight": var_cvar(portfolio_returns_eq),
    "CVaR Min": var_cvar(portfolio_returns_cvar),
    "CVaR + Target Return": var_cvar(portfolio_returns_cvar_target)
})

risk_tail

weights_table = pd.DataFrame({
    "Equal Weight": weights_eq,
    "CVaR Min": weights_cvar,
    "CVaR + Target Return": weights_cvar_target
}, index=returns.columns)

weights_table