# -*- coding: utf-8 -*-
"""Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Talk_to_Gemini_with_Google's_Speech_to_Text_API.ipynb

# 1. Eventos Fed Days
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ticker = "SPY"

prices = yf.download(
    ticker,
    start="2018-01-01",
    end="2025-12-31",
    auto_adjust=True
)["Close"]

prices = prices.squeeze()

returns = prices.pct_change().dropna()

event_dates = [
    "2018-03-21", "2018-06-13", "2018-09-26", "2018-12-19",
    "2019-03-20", "2019-06-19", "2019-07-31", "2019-09-18", "2019-10-30",
    "2020-03-15", "2020-04-29", "2020-06-10", "2020-09-16", "2020-12-16",
    "2021-03-17", "2021-06-16", "2021-09-22", "2021-12-15",
    "2022-03-16", "2022-06-15", "2022-09-21", "2022-12-14",
    "2023-03-22", "2023-06-14", "2023-09-20", "2023-12-13",
    "2024-03-20", "2024-06-12", "2024-09-18", "2024-12-18",
    "2025-03-19", "2025-06-18", "2025-09-17", "2025-12-17"
]

event_dates = pd.to_datetime(event_dates)

event_results = []

for event in event_dates:
    if event not in prices.index:
        continue

    event_price = prices.loc[event]

    row = {"Event Date": event}

    for horizon in [1, 2, 3, 5, 10]:
        future_dates = prices.index[prices.index > event]

        if len(future_dates) >= horizon:
            future_date = future_dates[horizon - 1]
            future_price = prices.loc[future_date]
            row[f"Return_{horizon}d"] = future_price / event_price - 1

    event_results.append(row)

event_df = pd.DataFrame(event_results)

event_df.head()

summary_events = event_df[[f"Return_{h}d" for h in [1,2,3,5,10]]].agg(
    ["mean", "median", "std", "min", "max"]
)

summary_events

hit_rate = (event_df[[f"Return_{h}d" for h in [1,2,3,5,10]]] > 0).mean()
hit_rate

avg_returns = event_df[[f"Return_{h}d" for h in [1,2,3,5,10]]].mean()

plt.figure(figsize=(8,5))
plt.plot([1,2,3,5,10], avg_returns.values, marker="o")
plt.title("Average SPY Return After FOMC Events")
plt.xlabel("Days After Event")
plt.ylabel("Average Return")
plt.grid(True)
plt.show()

"""# 2. Regímenes"""

def classify_period(date):
    year = date.year

    if year == 2020:
        return "Crisis"
    elif year == 2022:
        return "Tightening"
    elif year in [2019, 2021, 2023, 2024, 2025]:
        return "Normal / Easing"
    else:
        return "Other"

event_df["Period"] = event_df["Event Date"].apply(classify_period)

event_df.groupby("Period")[[f"Return_{h}d" for h in [1,2,3,5,10]]].mean()

event_df.groupby("Period")[[f"Return_{h}d" for h in [1,2,3,5,10]]].apply(lambda x: (x > 0).mean())

"""# 3. Distribución por Periodo"""

horizon = "Return_5d"

plt.figure(figsize=(10,6))

for period in event_df["Period"].unique():
    subset = event_df[event_df["Period"] == period]
    plt.hist(subset[horizon], bins=10, alpha=0.5, label=period)

plt.axvline(0, linestyle="--")
plt.title("Distribución de retornos 5D post-FOMC por régimen")
plt.xlabel("Retorno 5D")
plt.ylabel("Frecuencia")
plt.legend()
plt.grid(True)
plt.show()

event_df[["Event Date", "Period", "Return_1d", "Return_2d", "Return_5d", "Return_10d"]].sort_values("Return_5d")

"""# 4. Estrategia Basada en Eventos"""

event_df["Signal"] = (event_df["Period"] == "Normal / Easing").astype(int)

event_df[["Event Date", "Period", "Signal"]].head()

event_df["Strategy_Return"] = event_df["Signal"] * event_df["Return_5d"]

event_df[["Event Date", "Period", "Return_5d", "Strategy_Return"]].head()

event_df = event_df.sort_values("Event Date")

event_df["Strategy_Cum"] = (1 + event_df["Strategy_Return"]).cumprod()
event_df["Benchmark_Cum"] = (1 + event_df["Return_5d"]).cumprod()

plt.figure(figsize=(10,5))

plt.plot(event_df["Event Date"], event_df["Strategy_Cum"], label="Strategy")
plt.plot(event_df["Event Date"], event_df["Benchmark_Cum"], label="All Events")

plt.title("Estrategia FOMC vs Benchmark")
plt.legend()
plt.grid(True)
plt.show()

def performance_metrics(returns, periods_per_year=252):
    returns = returns.dropna()

    cumulative_return = (1 + returns).prod() - 1
    years = len(returns) / periods_per_year
    cagr = (1 + cumulative_return) ** (1 / years) - 1

    volatility = returns.std() * np.sqrt(periods_per_year)
    sharpe = cagr / volatility

    cumulative = (1 + returns).cumprod()
    peak = cumulative.cummax()
    drawdown = cumulative / peak - 1
    max_drawdown = drawdown.min()

    return pd.Series({
        "Cumulative Return": cumulative_return,
        "CAGR": cagr,
        "Volatility": volatility,
        "Sharpe": sharpe,
        "Max Drawdown": max_drawdown
    })

strategy_returns = event_df["Strategy_Return"]
benchmark_returns = event_df["Return_5d"]

metrics_events = pd.DataFrame({
    "Strategy": performance_metrics(strategy_returns.dropna()),
    "All Events": performance_metrics(benchmark_returns.dropna())
})

metrics_events